### ISSUE TITLE
UI do not open

### ISSUE THREAD

**Issue by joaovarelas** [hslbck/gnome-shell-extension-radio#101]
Hello, I've added several radios (let's say 20+) and now when I click on the icon the UI simply doesn't show up.
I think its because the list is too large and there is no scroll.
Where is located the file containing all the station URL's so I can remove manually?

Regards

**Comment by joaovarelas** [comment]
EDIT: Ok I found the `channelList.json` file located at `~/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/`

I tried to reset everything, reinstall extension (through Firefox & manually using .zip) nothing works. I cannot open the radio interface. The only thing that show up is the small icon in taskbar...

**Comment by hslbck** [comment]
Hi,

thanks for your feedback. I'll check if it's not too much effort to implement a scrollbar here without ruining the whole UI.

Originally it was intended that there are only a few starred channels in the list which are used most frequently. If one channel is not needed this often the list dialog of added channels should be used instead

**Comment by joaovarelas** [comment]
Hello,

I'm not sure about the scrollbar. At least in the main UI. Although there is a possibility to use an arrow, "dropdown" style. e.g

![image](https://user-images.githubusercontent.com/6439813/34651982-2f632a22-f3d0-11e7-9b26-021a05f957e3.png)

**Comment by hslbck** [comment]
In old releases the "dropdown" menu was used for starred channels. This was dropped, because it's an unnecessary extra click to switch channels. But when I got some time I will look into the scrollbar solution.

BR

**Comment by hslbck** [comment]
Only "dropdown" menu supports scrollbar by default. But the current solution allows a quicker access of favourites. Dropdown won't be used in the future

**Comment by joaovarelas** [comment]
I've been using it without "starring" all the channels. With the current solution the favorite channels must be limited else the window will go over the screen size limit.

Well I think it's not really important. Plugin is working great anyway.

Thanks
