### ISSUE TITLE
Button to copy current playing title to clipboard

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#102]
Hi,

Sometimes, I'm listening to a radio, and suddenly, I hear a song and I'm like: I want to be able to listen this again. So I look at the title, and write it somewhere. It's sometimes not very easy as each time you click somewhere, it closes the radio panel with the title ; and moreover, if it's too long, the whole title isn't displayed.

So, we could add a button "copy to clipboard", which would copy the title of the current song to the clipboard.

In the case where the title is empty, we could replace it by something like: radio name + current time. A lot of radio don't have ID3 tags in their stream, but still, display the list of (time, song) played on their website. So this information is sufficient to retrieve the song. E.g. [TSF Jazz](http://www.tsfjazz.com/quel-etait-ce-titre.php).

**Comment by hslbck** [comment]
Hi,

this was already requested some time before, maybe on the extension webpage :)
An easy solution would be to just add an entry to the titleMenu, like "Copy" which does exactly that. Would this be sufficient for you? 
A more complex and probably nicer solution would be to add a small button after the title in the regular radioMenu. Here some more layouting work has to be done.

BR

**Comment by hslbck** [comment]
Hi,

Implemented this feature with the latest commit. Now it is possible to copy the title by clicking the button in the radio menu or by middle clicking the title in the panel.

The button styling for long titles in the radio menu still needs some improvement though.

BR

**Comment by zapashcanon** [comment]
Hi, I just tested the two buttons, seems all good. :) Thanks !

**Comment by zapashcanon** [comment]
There's just one thing, it seems that it's the formatted text which is copied to the clipboard, i.e. with line breaks added to the text so it fits into the menu. Could it be possible instead to get the original text with no line break added ?

**Comment by hslbck** [comment]
Changed it :)

**Comment by zapashcanon** [comment]
It's perfect, thanks ! :D
