### ISSUE TITLE
copy "artists - songname" to clipboard does not work (for me)

### ISSUE THREAD

**Issue by Feichtmeier** [hslbck/gnome-shell-extension-radio#104]
Hi, awesome extension!
The menubar name middle click to copy to clipboard does not work for me:

Ubuntu 17.10 - shell version 17.10.2

**Comment by zapashcanon** [comment]
Hi,

Does it work when clicking on the icon in the extension menu ? The white icon right to the title:

![capture du 2018-02-07 21-40-21](https://user-images.githubusercontent.com/16472988/35940482-9afc73aa-0c4f-11e8-9510-e61bf9e269a4.png)

Are you using Wayland ?

Also, just to be sure we're talking about the same thing, you're middle-clicking on the title of the song, right ? Like the red thing here:

![capture du 2018-02-07 21-42-40-bis](https://user-images.githubusercontent.com/16472988/35940646-2498e5b2-0c50-11e8-872c-fa3002b7bf21.png)

**Comment by Feichtmeier** [comment]
Hi there,

no I am using xorg with ubuntu 17.10

Actually there is no + icon for me - very strange. Changed the gtk and icon themes - still no icon.
Yes I use the middle click :) The same button that works very well to stop/play the radio when middle clicked on the radio symbol

![bildschirmfoto von 2018-02-07 21-47-27](https://user-images.githubusercontent.com/15329494/35941004-38e6e234-0c51-11e8-9236-4361f2949a77.png)

**Comment by zapashcanon** [comment]
On my screenshot, the  `+` is part of the title (people from Radio Bach doing strange things :p). I was talking about this:

![capture du 2018-02-07 21-56-32](https://user-images.githubusercontent.com/16472988/35941202-ca24fb3c-0c51-11e8-82d8-6e45f26713e9.png)

**Comment by Feichtmeier** [comment]
Oh ok, well that one is also not there : / I tried to middle click all places around the title, no copy sadly :(

**Comment by zapashcanon** [comment]
How did you get the extension ? Copy and paste is new and hasn't been released yet. You can have it only by installing from source. My guess is that you installed it from the gnome-shell extension website and so, this feature is not implemented.

**Comment by Feichtmeier** [comment]
Oh, yes! Sorry, I did not realize this! I will remove it and manually add it from github then :)
I guess we can close this then :)

**Comment by zapashcanon** [comment]
Yep', you can close it then - I can't.

Once my current PR is merged, I'll ask @hslbck if he can release a new version as I'll need one for the Debian packaging, so, you can also wait a few days to get a new one on the website.

**Comment by Feichtmeier** [comment]
Okay, maybe I will just wait then :)

**Comment by hslbck** [comment]
Hi,

yes this feature was introduced recently. How to install this extension from source you can have a look at https://github.com/hslbck/gnome-shell-extension-radio/blob/master/CONTRIBUTING.md

@zapashcanon thanks for your help :)
