### ISSUE TITLE
Multiple streams running / Stream not stopped/canceled properly

### ISSUE THREAD

**Issue by cinatic** [hslbck/gnome-shell-extension-radio#105]
Hello,

this extension is awesome, thanks for your effort!

I noticed that when i play a stream and it's not reacting idk maybe slow connection and meanwhile clicked another stream it can happen that they play in parallel, maybe because the first request was not cancelled?

Best regards

**Comment by cinatic** [comment]
i know have two stream and don't know how to stop them (don't want to refresh shell), stop button is stopping only one

**Comment by zapashcanon** [comment]
I can confirm this.

**Comment by hslbck** [comment]
Hi,

I try if I can reproduce this issue, could be related that one stream is not disconnect properly. I don't know how GStreamer is handling streams for slow connections. By the way which GNOME shell version are you using, Gstreamer version and extension version?

**Comment by cinatic** [comment]
I am using Version 8, directly from extension.gnome.org

```extra/clutter-gst 3.0.24-1 [installed]
extra/gnome-video-effects 0.4.3-1 [installed]
extra/gst-libav 1.12.4-1 [installed]
extra/gst-plugins-bad 1.12.4-3 [installed]
extra/gst-plugins-base 1.12.4-1 [installed]
extra/gst-plugins-base-libs 1.12.4-1 [installed]
extra/gst-plugins-good 1.12.4-1 [installed]
extra/gst-plugins-ugly 1.12.4-3 [installed]
extra/gstreamer 1.12.4-1 [installed]
extra/phonon-qt5-gstreamer 4.9.0-3 [installed]
extra/totem 3.26.0+1+g4e309671-1 (gnome) [installed]
aur/gstreamer0.10 0.10.36-17 [installed] (75) (5.72)
aur/gstreamer0.10-base 0.10.36-11 [installed] (82) (4.92)
aur/gstreamer0.10-base-plugins 0.10.36-11 [installed] (82) (4.92)
-----
extra/gnome-shell 3.26.2+14+g64c857e3f-1 (gnome) [installed]
extra/gnome-shell-extensions 3.26.2+9+g683b5ee-1 (gnome) [installed]
```

only a idea: some kind of clean/reset button in the menu or a play and stop icon, and stop will always stop every stream
