### ISSUE TITLE
Adding the same radio twice will lead to strange things

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#106]
Hi,

If you search a station, let's say `TSF Jazz`, add it as a favorite. Close the window. Then, add it a second time still as a favorite.

It'll lead to strange things like: it'll appear 3 times in the favorite list. If you delete it once, it'll delete all of them etc.

One solution would be to disallow adding two stations with the same name. Another one would be to add an ID to each entry in the channel list and stop identifying them by name.

**Comment by hslbck** [comment]
Hi,

is it a use case to add the same station multiple times ;)
But yes you're right, introducing a ID would be better, but this means changing the methods to work on id level and making sure that no configured stations will be lost when the extensions gets updated via the extension webpage.

**Comment by zapashcanon** [comment]
Yes actually it was a real use case for me too, but it kinda messed up the favorite list and deleting one lead to wrong behaviour too. I'll try to have a look at how the code can be uptaded to use ID next week.

**Comment by hslbck** [comment]
Hi,

adding a radio station with the same name works now. If you encounter any problems, please get back to me.

Best regards

**Comment by zapashcanon** [comment]
Hi,

It seems to work well, thanks ! :)

I noticed something probably unrelated: when searching some station to add, now the favorite icon is on by default, is this new ? But anyway, IMO it's better like this!

**Comment by hslbck** [comment]
yes i changed the default behaviour for favorites :)
