### ISSUE TITLE
Issue: After suspend cannot play radio

### ISSUE THREAD

**Issue by pszafer** [hslbck/gnome-shell-extension-radio#11]
Hello,

After wake up from suspend mode, when I try play radio station it hangs gnome-shell.
I have to restart gdm or computer to work again.

Is it possible to somehow restart instance of radio?

gnome-shell --version
GNOME Shell 3.18.3

**Comment by hslbck** [comment]
Hi,

you disable/enable the extension via "https://extensions.gnome.org" or the "Tweak Tool".
Another solution (quicker) would be just to reload gnome-shell by entering "r" into that pops up when you press  "Alt+F2"

When you go into suspend mode, did you stop playing the radio stream or was it currently running?
Do you have other gnome-shell extensions installed? Is it possible for you to provide me log information from journalctl?

**Comment by pszafer** [comment]
This is what I see when I try play radio after suspend (buefore suspend I stopped playing):
```
gru 14 09:46:11 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > refresh indicator -A false -F true
gru 14 09:46:11 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > refresh indicator -A false -F false
gru 14 09:46:13 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > refresh indicator -A false -F true
gru 14 09:46:13 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > refresh indicator -A false -F false
```

**Comment by pszafer** [comment]
I have little more logs, maybe to you it'll say something
```
gru 17 09:27:42 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > mixer stream remove - ID: 694
gru 17 09:27:42 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > mixer stream remove - ID: 694

gru 17 09:30:12 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > refresh indicator -A false -F true
gru 17 09:30:12 PCNAME gnome-session[755]: Gjs-Message: JS LOG: ESC > refresh indicator -A false -F false
```

**Comment by hslbck** [comment]
I still could not reproduce it and the log messages are to generic. I can't tell for sure if the extensions is causing these error messages 

Do you use other gnome shell extensions besides "Internet Radio"?
Does the extensions hang for one specific stream / radio station?

**Comment by pszafer** [comment]
Hello,
Sorry for late response...

Answers for your questions:
- yes I use other extensions: drop down terminal, dash to dock, openweather, refresh wifi connections, sound output chooser, application menu.
- no, as far as I checked extension hang for most of my radio stations.

One more thing, I use lightdm, not gdm and I have nvidia graphic card.

**Comment by hslbck** [comment]
Hi,

try to disable the other extensions in use and check if the error is still occuring. One older issue was related to the interference of other extensions.

What gstreamer do you have installed? Lightdm could be a issue here,too.
