### ISSUE TITLE
Notify Title Change   Improvement request

### ISSUE THREAD

**Issue by lsatenstein** [hslbck/gnome-shell-extension-radio#114]
Currenly when the music is playing, it flashes the title, and it does it over and over and over, virtually twice per second.
.
Can you provide a way for the extension to compare the current music title to the previous one, and to only post the alert if there is a change.

**Comment by hslbck** [comment]
the extension should already compare if the title changed and only show a new notification if it has change. 
Can you provide the radio station where this is happening?
