### ISSUE TITLE
Support for keyboard media keys?

### ISSUE THREAD

**Issue by orschiro** [hslbck/gnome-shell-extension-radio#116]
Dear @hslbck,

Would you be able to support keyboard media keys to control the playback?

For example, my Thinkpad X230 has a special key triggered by `Fn + F11` to pause/play music playback. 

It would be great being able to control the radio that way. :-)

Thank you!

**Comment by zapashcanon** [comment]
Hi,

This feature is already here. It's probably just not enabled: try to go to the extension's settings using GNOME Tweak Tool and enable it. :)

**Comment by orschiro** [comment]
Dear Leo, 

Thank you so much!

Please apologise for the screenshot in French. 

I have enabled the setting which should be the correct one and restarted the shell with the `r` command. 

However, my `Fn + F11` is still not functional. 

Do you have any ideas what else I could try to debug it?

Thank you!

![image](https://user-images.githubusercontent.com/170947/44074353-879dcc5a-9f98-11e8-94e2-43c8c287dccf.png)

**Comment by orschiro** [comment]
Leo, please disregard my comment. 

I had to restart my laptop. Now they are working. :-)

Thank you so much!

**Comment by hslbck** [comment]
@zapashcanon thanks for taking care :+1:

**Comment by zapashcanon** [comment]
Great. :)

@orschiro: le français étant ma langue maternelle, le screenshot n'est pas un problème. ;)
