### ISSUE TITLE
Does not work out of the box on Pop!_OS 18.04 LTS

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [hslbck/gnome-shell-extension-radio#117]
As I understand it, Pop!_OS is just a customized version of Ubuntu, so I'd expect this extension to work out of the box.

It is a recommended extension for Pop!_OS. See here:

[Recommended GNOME extension does not install #345](https://github.com/pop-os/pop/issues/345)

The error is:

Extension "radio@hslbck.gmail.com" had error: Error: Requiring GstPbutils, version none: Typelib file for namespace 'GstPbutils' (any version) not found

Here is what gstreamer packages are installed:

`apt list --installed | grep gstreamer`
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-gstreamer-1.0/bionic-updates,now 1.14.1-1~ubuntu18.04.1 amd64 [installed,automatic]
gstreamer1.0-alsa/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed]
gstreamer1.0-clutter-3.0/bionic,now 3.0.26-1 amd64 [installed,automatic]
gstreamer1.0-gl/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
gstreamer1.0-plugins-base/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
gstreamer1.0-plugins-base-apps/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed]
gstreamer1.0-plugins-good/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,autom[installed,automatic]atic]
gstreamer1.0-pulseaudio/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
gstreamer1.0-tools/bionic-updates,now 1.14.1-1~ubuntu18.04.1 amd64 [installed,automatic]
gstreamer1.0-x/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
libgstreamer-gl1.0-0/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
libgstreamer-plugins-base1.0-0/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
libgstreamer-plugins-good1.0-0/bionic-updates,now 1.14.1-1ubuntu1~ubuntu18.04.1 amd64 [installed,automatic]
libgstreamer1.0-0/bionic-updates,now 1.14.1-1~ubuntu18.04.1 amd64 [installed,automatic]
libreoffice-avmedia-backend-gstreamer/bionic,now 1:6.0.3-0ubuntu1 amd64 [installed,automatic]
```

**Comment by zapashcanon** [comment]
Hi,

How did you install the extension ?

**Comment by Bananas-Are-Yellow** [comment]
I added the Chromium plugin and then I used the On/Off slider at the top-right of your [extension page](https://extensions.gnome.org/extension/836/internet-radio/). I tried again just now and the slider turns into a red Error indicator. Then I have to refresh the page in order to get the X button to uninstall it.

**Comment by hslbck** [comment]
What is your output when you enter `imports.gi.GstPbutils` in looking glass?
Looking glass can be opened by pressing `alt+f2` and entering `lg`

**Comment by hslbck** [comment]
ok I tried pop os in a virtual machine. Enter `imports.gi.GstPbutils` in looking glass leads to an error. I solved this by installing the package `gir1.2-gst-plugins-base-1.0`. Please check if this works for you

**Comment by Bananas-Are-Yellow** [comment]
Yes, I also got an error entering `imports.gi.GstPbutils` in the looking glass.

Installing `gir1.2-gst-plugins-base-1.0` fixes the error. The internet radio now works.

Thanks.

**Comment by hslbck** [comment]
great :)

**Comment by Bananas-Are-Yellow** [comment]
What is the outcome? Will your extension automatically install the required package now, or do people have to do this manually?

**Comment by hslbck** [comment]
Extensions cannot automatically install required packages when installed from the extension webpage by design. This is only possible, if the extension is packaged by the distribution itself, like it's done for Archlinux. The package names also are different on different distributions.
For now the user has to make sure that the plugins are available, as it's stated on the extension README page.
