### ISSUE TITLE
Feature request: add Spotify support

### ISSUE THREAD

**Issue by Feichtmeier** [hslbck/gnome-shell-extension-radio#119]
I know this is a weird request, but do you think it would be technically possible to add support for Spotify? 
Like search a spotify radio ?
They can basically build radio streams out of any song/artist :)
Feel free to close it if it's not possible or out of scope :)
Best regards

**Comment by hslbck** [comment]
If Spotify has an API for that, it would be possible. But I don't know if such an API exists and if there are some restrictions on using it. 
I will keep this issue open for now until I checked the API, but chances are high that support for Spotify won't be added

**Comment by zapashcanon** [comment]
Spotify [has an API](https://developer.spotify.com/documentation/web-api/reference/) for various stuff. But they won't let you stream the audio and play it from the extension (or if the extension get white-listed, we can play 30 sec. previews) . The only thing that can be done is to control a *player*, that is to say, you'll have to open Spotify on your computer or your mobile phone, then you would have to select the one you want in the extension, then, it would be possible do to things like pause, resume, move to the next song etc. using the API. But all of this would still need Spotify to be open on a device.

**Comment by Feichtmeier** [comment]
@zapashcanon thanks for the info!

**Comment by hslbck** [comment]
@zapashcanon thanks for looking this up. I'm closing the issue, because the extension is not intended to control a separate player.
