### ISSUE TITLE
Add channels externally

### ISSUE THREAD

**Issue by mikeymckay** [hslbck/gnome-shell-extension-radio#120]
I have written a little script that gets the daily URL for a stream I like to listen to. I can then append an entry into channelList.json. But the new entry doesn't appear unless I manually restart the extension. Is there any way to force the channelList to reload without the old "have you tried turning it off and on again"?

Here's how I update the channel list (get a json file, extract the location, and append it to channelList):
`jq ".channels += [{\"id\":\"1\", \"name\":\"Morning Becomes Eclectic\", \"address\":$(cat kcrw.json | jq ".media[0].url"), \"favourite\":true, \"encoding\":false}] " ~/.gse-radio/channelList.json > /tmp/tmp.json && mv /tmp/tmp.json ~/.gse-radio/channelList.json`

**Comment by hslbck** [comment]
The channel list is loaded on the initialization of the extensions. When a channel is added the extension takes care to reload the list, but this is not the case for your script.

A solution that could work for you, is that you disable and enable the extension in your script by using the `gnome-shell-extension-tool`, e.g. add following lines to your script `gnome-shell-extension-tool disable radio@hslbck.gmail.com` and `gnome-shell-extension-tool enable radio@hslbck.gmail.com`.
