### ISSUE TITLE
Can't find station correctly

### ISSUE THREAD

**Issue by emersoncavalcanti1972** [hslbck/gnome-shell-extension-radio#121]
When I perform a radio search (eg BandNews) the application returns "No server stream address found". But this radio exists in the "Radio Browser Info". Other radios are located correctly. If it persists, the gnome-shell application freeze.

**Comment by hslbck** [comment]
It seems that the extension cannot handle or find the stream for the provided station. This means when the m3u or pls file is parsed from radio-browser it doesn't find a proper stream location.

For the application freeze, I also had those. Solution would be to move the station search to the settings window, but this requires some rewriting

**Comment by emersoncavalcanti1972** [comment]
It's ok. Thanks for the feedback. Here's what you can do to give your users the best experience when using this extension. I have never programmed extensions for Gnome but I am a Javascript programmer and if I can help, I am available.
