### ISSUE TITLE
Extension m3u lost after change radio

### ISSUE THREAD

**Issue by pbillerot** [hslbck/gnome-shell-extension-radio#122]
If the stream extension is .m3u, the extension is lost after the update

Before
```
{
	"id": "64d8d4cd-8853-42be-bfef-079cf4f9f60a",
	"name": "OUI FM Acoustic",
	"address": "http://rmye2.infomaniak.ch:80/ouifmacoustic.m3u",
	"favourite": true,
	"encoding": false
}
```
After
```
{
	"id": "64d8d4cd-8853-42be-bfef-079cf4f9f60a",
	"name": "OUI FM Acoustic",
	"address": "http://rmye2.infomaniak.ch:80/ouifmacoustic\r",
	"favourite": true,
	"encoding": false
}
```

```
inxi -F
System:    Host: pcbox Kernel: 4.15.0-42-generic x86_64 bits: 64 Desktop: Gnome 3.28.3
           Distro: Ubuntu 18.04.1 LTS
Machine:   Device: desktop Mobo: ASRock model: 880GMH/U3S3 serial: N/A BIOS: American Megatrends v: P1.40 date: 06/08/2011
CPU:       Triple core AMD Athlon II X3 455 (-MCP-) cache: 1536 KB
           clock speeds: max: 3300 MHz 1: 2100 MHz 2: 2100 MHz 3: 800 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RS880 [Radeon HD 4250]
           Display Server: x11 (X.Org 1.19.6 ) driver: radeon Resolution: 1920x1200@59.95hz
           OpenGL: renderer: AMD RS880 (DRM 2.50.0 / 4.15.0-42-generic, LLVM 6.0.0) version: 3.3 Mesa 18.0.5
Audio:     Card-1 Advanced Micro Devices [AMD/ATI] RS880 HDMI Audio [Radeon HD 4200 Series]
           driver: snd_hda_intel
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA) driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.15.0-42-generic
Network:   Card: Qualcomm Atheros AR8151 v2.0 Gigabit Ethernet driver: atl1c
           IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: 00:25:22:eb:b8:a3
```

**Comment by zapashcanon** [comment]
Hi,

> after the update

Which update are you talking about ? Editing the radio station ?

**Comment by hslbck** [comment]
Do you add the station manually using the GUI (+ icon) and provide the m3u file?

The extension parses the m3u file and stores the real stream address without the m3u extension. You can see it, when you download the m3u file and open it with a text editor.

**Comment by pbillerot** [comment]
Merci pour votre réactivité,
Le problème se passe quand je change de station. Quand je réactive la précédente parfois j'ai une "stream error". Après beaucoup d'essais le problème est aléatoire. 
Je suis désolé de vous avoir sollicité pour un problème lié peut-être à la station radio ou à la qualité du réseau.
Cordialement.
----
Thank-you for your prompt response,
The problem happens when I switch stations. When I reactivate the previous one sometimes I have a "stream error". After a lot of tests the problem is random.
I'm sorry to have asked you for a problem that may be related to the radio station or the quality of the network.
Cordially.
