### ISSUE TITLE
Plugin icon

### ISSUE THREAD

**Issue by TeknoMobil** [hslbck/gnome-shell-extension-radio#123]
Hi
add-on icon in system tray does not appear
Gnome 3.32

**Comment by hslbck** [comment]
GNOME 3.32 is not yet supported by the extension.
There is probably an error happening when the extension is loaded and therefore it is not displayed in the panel. You should be able to see the error in the system logs.
When GNOME 3.32 is released I will add support for it

**Comment by TeknoMobil** [comment]
Thank you, this plugin is very nice
Respects
