### ISSUE TITLE
Gnome 3.32, icon not appearing

### ISSUE THREAD

**Issue by coxackie** [hslbck/gnome-shell-extension-radio#124]
Arch with GNOME 3.32, extension works, but icon in top bar does not appear.

**Comment by TeknoMobil** [comment]
Adding and editing new stations does not work. Gnome 3.32 js library incompatible.

One of my favorite add-ons

**Comment by coxackie** [comment]
Indeed, confirming that apart from streaming the other operations do not work.

**Comment by TeknoMobil** [comment]
The developer will fix it, I'm waiting ;)

**Comment by hslbck** [comment]
Thanks for reporting. Seems that the usage of `Lang.class` has to be refactored. I will check it and provide an update as soon as I get to it

**Comment by hslbck** [comment]
Icon should be back again on latest master version

**Comment by TeknoMobil** [comment]
Thank you very much, it works perfectly :+1: 
![Ekran Görüntüsü - 2019-03-21 00-43-51](https://user-images.githubusercontent.com/42881121/54721237-769f0a00-4b72-11e9-847a-b1a01d4d6211.png)

**Comment by coxackie** [comment]
Can also confirm that it works - many thanks. Are you going to submit to gnome shell extensions for review?

**Comment by hslbck** [comment]
New version is up for review on gnome shell extensions page
