### ISSUE TITLE
Not working, says missing plugin

### ISSUE THREAD

**Issue by sandikata** [hslbck/gnome-shell-extension-radio#127]
Same as description.
Not working, missing plugin. What plugin ?

**Comment by hslbck** [comment]
Plugin depends on the stream audio format you want to listen to. Installing gst-plugins-bad, gst-plugins-good and gst-plugins-ugly should provide all required formats. 
Could be that you need to restart gnome-shell in order for the plugins to work

**Comment by sandikata** [comment]
i have installed all of this plugins, and gnome-shell restarted. same think.

**Comment by hslbck** [comment]
What gnome-shell and extension version are you running? Which gstreamer plugin version do you have installed? Is any other stream working?

**Comment by sandikata** [comment]
gnome 3.30
extension for 3.30

root on GA-990-FXA-UD3-FX8320 in ~
$ eix gst-plugins-bad    
[I] media-libs/gst-plugins-bad [1]
     Available versions:  
     (0.10) 0.10.23-r4
     (1.0)  1.14.1-r1^t (~)1.14.2^t (~)1.14.3^t
       {X bzip2 +egl gles2 gtk +introspection nls +opengl +orc test vcd vnc wayland ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  1.14.3(1.0)^t( 2:20:14 22.03.2019)(X bzip2 egl gtk introspection nls opengl orc wayland -gles2 -test -vcd -vnc ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            https://gstreamer.freedesktop.org/
     Description:         Less plugins for GStreamer

[1] "media-kit" /var/git/meta-repo/kits/media-kit
root on GA-990-FXA-UD3-FX8320 in ~
$ eix gst-plugins-ugly
[I] media-libs/gst-plugins-ugly [1]
     Available versions:  
     (0.10) 0.10.19-r1
     (1.0)  1.14.1 (~)1.14.2 (~)1.14.3
       {nls +orc ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  1.14.3(1.0)( 7:57:32  8.04.2019)(nls ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            https://gstreamer.freedesktop.org/
     Description:         Basepack of plugins for gstreamer

[1] "media-kit" /var/git/meta-repo/kits/media-kit
root on GA-990-FXA-UD3-FX8320 in ~
$ eix gst-plugins-good
[I] media-libs/gst-plugins-good [1]
     Available versions:  
     (0.10) 0.10.31-r2
     (1.0)  1.14.1 (~)1.14.2 (~)1.14.3 (~)1.14.4
       {nls +orc ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  1.14.4(1.0)( 2:15:11 22.03.2019)(nls orc ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            https://gstreamer.freedesktop.org/
     Description:         Basepack of plugins for GStreamer

[1] "media-kit" /var/git/meta-repo/kits/media-kit
root on GA-990-FXA-UD3-FX8320 in ~
$

**Comment by hslbck** [comment]
Which radio stream is not working? Or are all not working?

Check for gst-plugin-base and gst-plugin-base-libs as well

**Comment by sandikata** [comment]
all of them not work.

**Comment by shamnad-sherief** [comment]
Got the same error **Missing Plugin**

Reading the comments, found that the issue is with .m3u8 files.  Installing the plugin `gstreamer1.0-plugins-bad` worked.

`sudo apt install gstreamer1.0-plugins-bad`

Don't forget to restart your shell to work.
