### ISSUE TITLE
Station and Songinfos to long in panel

### ISSUE THREAD

**Issue by Etamuk** [hslbck/gnome-shell-extension-radio#129]
Hello,

first of all i want to thank you for this great extension. Very nice tool :+1: .
To my report:
I activated the menu to show songinfos and stationname in panel. After that this infos are overlapping the clock. 
Please see my screenshot. 
Solution: Only the Songinfos and stationname as option. 

![Bildschirmfoto von 2019-06-23 18-07-52](https://user-images.githubusercontent.com/20098065/59979106-8d2a8680-95e3-11e9-829d-9e9031ac4acb.png)

**Comment by hslbck** [comment]
Hi,

does this issue persist when you deactive all other extensions? Do you have some extension installed which changes the order of the panel?
Reason is I cannot reproduce this issue for default installations even with long texts, e.g. for Radio Bach.

Making the stationname optional could improve the situation a bit in your case, but it doesn't  solve it entirely

**Comment by Etamuk** [comment]
Hi, 
when i deactivate all other extensions it's ok (for the time of listening, it's hard to find songs with very long names). In this case I think it's because there is enough space for station and song info. If activated other extensions wich come with an indicator icon the extensions will have to divide the space. 
Or maybe the clock has no "boundary" which tells other extensions his position.

**Comment by hslbck** [comment]
Even for long titles this is no issue for me, the text is properly shortened before the clock. This is probably because I don't use many extensions for the panel.

I think the sorting after startup depends when an extension gets initialized.
