### ISSUE TITLE
Support Old Gnome

### ISSUE THREAD

**Issue by Brainwall** [hslbck/gnome-shell-extension-radio#13]
Please support LTS version Gnome shell like Ubuntu Gnome and Debian Gnome.

Debian - Gnome Shell version : 3.14
Ubuntu LTS - Gnome Shell version 3.10

This is very important as it LTS OS system... thx very much...

**Comment by hslbck** [comment]
You can try to enable the extension manually by editing the metadata.json in ~/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com

Simply add 3.14 to your shell version entry like "shell-version": ["3.14", "3.16"]. 

The extension should work for 3.14. I can't tell if the extension is working with 3.10 and don't have a system with this quite old shell version.

But the upcoming Ubuntu LTS release (probably with gnome-shell  3.20) will be supported

**Comment by hslbck** [comment]
Added support for Gnome 3.14
