### ISSUE TITLE
issues after installing starlabs theme

### ISSUE THREAD

**Issue by abuakram** [hslbck/gnome-shell-extension-radio#130]
hi 
I really love your extension
But it stopped working after installing starlabs theme on ubuntu 19.04

**Comment by hslbck** [comment]
Hi,

Can you please provide more logs why it is not working anymore, e.g. via looking glass or journalctl. Run `journalctl | grep radio@hslbck` to get some log information about the extension. Maybe some plugin of gstreamer is missing

**Comment by abuakram** [comment]
Thanks for your response...
after executing your command I got the following:

`Error: Requiring Gst, version 1.0: Typelib file for namespace 'Gst', version '1.0' not found`

**Comment by abuakram** [comment]
installed gir1.2-gst-plugins-base-1.0

and voila, works perfectly

your tip to run journalctl was more than helpful

Thanks alot
