### ISSUE TITLE
Error: No signal 'value-changed' on object 'Gjs_Slider'

### ISSUE THREAD

**Issue by coxackie** [hslbck/gnome-shell-extension-radio#132]
In the recent update to GNOME 3.34, extension shows error and does not load. More precisely: `Error: No signal 'value-changed' on object 'Gjs_Slider`. Possibly similar to the issue here:
https://github.com/kiyui/gnome-shell-night-light-slider-extension/issues/48
which could have found a solution here:
https://github.com/kiyui/gnome-shell-night-light-slider-extension/pull/49

**Comment by hslbck** [comment]
The extension is still loading for me. Do you have the separate volume slider enabled? If yes try to disable it via dconf and reload the extension. Afterwards playing streams should be possible.
However it seems there are further issues with GNOME 3.34, e.g. channel list and search are not shown.

**Comment by Pednick** [comment]
Internet Radion isn't working with GNOME 3.34, are you aware of that?

**Comment by coxackie** [comment]
I can confirm that when the volume slider is disabled the extension.
