### ISSUE TITLE
Version 12 does not load on Gnome 3.32

### ISSUE THREAD

**Issue by sisou** [hslbck/gnome-shell-extension-radio#134]
It throws the following error and fails to load on Gnome 3.32.2:

```
TypeError: GObject.registerClass() used with invalid base class (is ModalDialog)
```

**Comment by sisou** [comment]
Quick instructions to downgrade to version 11:

* Download release 11 from https://extensions.gnome.org/extension-data/radiohslbck.gmail.com.v11.shell-extension.zip
* Press <kbd>Alt+F2</kbd> to open Gnome's command prompt
* Type `lg` as the command and press ENTER, this opens Gnome's "Looking Glass"
* In the overlay, go to 'Extensions'  in the top right
* Search for the "Internet Radio" extension and click on "View Source"
* A file explorer opens with the location of the extension's files
* Replace all of those files with the files from the downloaded version 11 ZIP file
* To reload the extension, either:
    * Enable via https://extensions.gnome.org/local/ (**do not** update the extention there!)
    * Enable via Gnome Tweak Tool
    * X window: press <kbd>Alt+F2</kbd> again, type `r` in the command, and press ENTER to reload the X window server
    * Wayland (e.g. Fedora): run `gnome-shell-extension-tool -r radio@hslbck.gmail.com`

**Comment by Ruud68** [comment]
I can confirm this also happens for version 3.32.**1**
@sisou thanks for sharing the workaround, works perfect!

**Comment by freddyw** [comment]
@sisou , thanks for the workaround. I can confirm the it is not working on 3.32.[1|2]. Is it working on 3.34.0 though, if you are brave enough to try fedora 31 Beta.

**Comment by RAD750** [comment]
Thanks for the workardound @sisou it works perfectly on Pop!_OS 19.04 :+1:

**Comment by hslbck** [comment]
@sisou Thanks for reporting the issue and already describing the workaround. I uploaded the code of version 11 with a new version 13 to the extension webpage. 
When it gets approved the latest version from the extension webpage should work for GNOME 3.32 again.

**Comment by sisou** [comment]
Cool, I just got vesion 13 installed by updating (from version 11)! :+1:
