### ISSUE TITLE
Multimedia key next with an IR remote

### ISSUE THREAD

**Issue by ventoux84** [hslbck/gnome-shell-extension-radio#136]
Hello,
Thank you for this beautiful extension.
On Ubuntu 18.04 and gnome-shell  3.28.4-0ubun amd64, i want to manage internet-radio with a IR remote.
All keys (Play/Pause, Mute ...) work well except next and previous.

My remote (with ir-keytable) sends the keycode "KEY_NEXT",  but internet-radio does not cycle through stations.
What is the code the remote has to send to change the station ?

Greetings
Ventoux84

**Comment by hslbck** [comment]
Hi,

For media keys support the extension uses gnome-settings-daemon, see https://github.com/GNOME/gnome-settings-daemon/tree/master/plugins/media-keys. Maybe sending the keycode "NEXT" or "NEXT_KEY" will work with the remote.

**Comment by ventoux84** [comment]
Thanks for this information.
Also in VLC or Totem, these keys next and previous are without any effect.
For others also :
https://askubuntu.com/questions/951432/ir-remote-some-media-keys-wont-work-key-nextsong-key-previoussong

Internet-radio does not seem to be in question.
Regards
