### ISSUE TITLE
Multimedia keys do not immediately work on a Gnome Shell 3.34

### ISSUE THREAD

**Issue by webmastak** [hslbck/gnome-shell-extension-radio#140]
The multimedia keys do not work after restarting the computer, until you open the extension settings and disable / enable multimedia key management or restart `Alt + F2 + r` the Gnome Shell. 

![https://i.imgur.com/Bxf1Va9.png](https://i.imgur.com/Bxf1Va9.png)

**Comment by hslbck** [comment]
Could reproduce the issue on X.org as well. Behaviour was previously only present for Wayland. I'll check if I can find something to solve this issue.

**Comment by webmastak** [comment]
I solved the problem a long time ago.
