### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by dezso-markon** [hslbck/gnome-shell-extension-radio#142]
I have all the gst plugins installed including base, but can't get it working. Tried with several different stations, same result: Missing plugin. Arch linux, Gnome 3.36

**Comment by hslbck** [comment]
What stream are you trying to listen too? On Arch linux pre configured station Byte FM for example works fine for me with GNOME 3.36

**Comment by Pednick** [comment]
> I have all the gst plugins installed including base, but can't get it working. Tried with several different stations, same result: Missing plugin. Arch linux, Gnome 3.36

I'm on gentoo btw, anyway I use to get that message of the missing plugin and I installed:

gst-plugins-hls

gst-plugins-soup

the I did the alt-F2 and typed in r to restart now it works, no missing plugin error message.
