### ISSUE TITLE
Internet Radio not working on Gnome 3.36 

### ISSUE THREAD

**Issue by ferlanero** [hslbck/gnome-shell-extension-radio#143]
Internet Radio actually gum up with Gnome search provider. If Internet Radio is installed, Gnome Search Provider doesn't show any result, so Internet Radio degrades the Gnome Experience.

It will be possible to search a solution as this is a great extension?

**Comment by hslbck** [comment]
Please deactive search provider for now then. Currently there is no support for GNOME 3.36 as I haven't had time to check on it

**Comment by hslbck** [comment]
Search provider is working fine for me with GNOME 3.36. Issue still present?

**Comment by junaru** [comment]
Working fine for me too.

**Comment by elpraga** [comment]
It is not working on Ubuntu 20.04 ATM. It does work after install, but it does not work after resume from suspend / hibernation.
(possibly also after restart) - it also causes GNOME Shell app search not work (it does not show any results)

**Comment by elpraga** [comment]
It also shows ERROR in the _Installed extensions_ web page. Is there more information I could provide? What king of information would be useful to you?

**Comment by junaru** [comment]
To my knowledge the extension at extensions.gnome.org is not updated for 3.36. The people reporting it working are using it in semi broken state.
Please remove it and install manually from this repo as per instructions at https://github.com/hslbck/gnome-shell-extension-radio/blob/master/CONTRIBUTING.md.
If it still not working search for extension errors with `journalctl -b |grep gnome-shell`

**Comment by hslbck** [comment]
Like @junaru  said, if issue still exists posting some logs from journalctl would be helpful regarding this extension
