### ISSUE TITLE
ERROR at install

### ISSUE THREAD

**Issue by j2l** [hslbck/gnome-shell-extension-radio#148]
Using Firefox or Chromium on PopOS (unbuntu) 19.10 with gnome-shell 3.34.3 and Gstreame plugins (bad, good, ugly, rtp), I get:
![radio fail](https://user-images.githubusercontent.com/65325/80862713-7d55e700-8c77-11ea-8a18-375e31261623.png)
There's no message in the console.

**Comment by junaru** [comment]
Try installing it manually by choosing your gnome and extension version, downloading the file and extracting its contents to:
`~/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/`

You will need to restart gnome afterwards. You can find more detailed steps [here](https://itsfoss.com/gnome-shell-extensions/) if you scroll down to "3. Install GNOME Shell Extensions manually" section.

**Comment by j2l** [comment]
Thank you.
Unfortunately, it still doesn't work

**Comment by hslbck** [comment]
Still having the issue? GNOME 3.34 should work fine from the extension page. Can you post your output from lg. Press alt+f2 and enter lg. Check Internet radio errors in extension tab

**Comment by j2l** [comment]
Sorry, don't have time anymore.
Maybe later

**Comment by j2l** [comment]
Hey,
Good news!

I've read on your page https://extensions.gnome.org/extension/836/internet-radio/ a recent comment that fix it for me. It wasn't working without the extension.
