### ISSUE TITLE
Realy big buttons in menu

### ISSUE THREAD

**Issue by Etamuk** [hslbck/gnome-shell-extension-radio#149]
Hello,
I updated my PopOS to the latest 20.04 with GNOME 3.36. 
After upgrading the buttons in the extension menu are very big. Please see my screenshot. 

I tried to reinstall the radio extension but after that the sender list was **not** gone (so maybe there is a place with further config files). 
![Bildschirmfoto von 2020-05-03 23-17-30](https://user-images.githubusercontent.com/20098065/80926221-27c42c00-8d96-11ea-8d7f-2bf95b2c79dd.png)

Perhaps it helps you: I am using a 4K-Screen.

**Comment by junaru** [comment]
> I tried to reinstall the radio extension

Did you reinstall the extension from github master repo?

>  the sender list was not gone

Can you explain this more? 

>  maybe there is a place with further config files

You can view all settings via
`$ dconf-editor /org/gnome/shell/extensions/radio`

>  I am using a 4K-Screen.

Tried on 4k tv with and without scaling, cant reproduce.

I would recommend getting the latest version from master and if that doesn't help try changing icon/gtk themes via `$ gnome-tweaks` to rule out any theme issues.

**Comment by Etamuk** [comment]
Hello,
thanks for your feedback.
I reinstalled it from official https://extensions.gnome.org/.

Meaning of "sender list was not gone": Maybe station list would be a better word for it. Sorry. After reinstalling of the extension I was able to start the radio and there was no need to add the stations again. They were stored. But I don´t know where. Shouldn´ t they been gone by removing the extension?

I testet various icon and gtk3 themes. I also installed from source. But all these steps doesn´ t bring a change.

Please see my screenshot with the settings: 
![Bildschirmfoto von 2020-05-07 14-05-43](https://user-images.githubusercontent.com/20098065/81292452-ea98bc00-906b-11ea-8496-6d65a07c649a.png)

**Comment by junaru** [comment]
> I reinstalled it from official https://extensions.gnome.org/.

The version at https://extensions.gnome.org/ is not updated for GNOME 3.36. 
You need to clone the master repository, run `$ make install`, restart gnome-shell and enable the extension via `$ gnome-tweaks`

The station list is kept at `~/.gse-radio/channelList.json` so you won't loose it during reinstalls.

**Comment by Etamuk** [comment]
> The station list is kept at `~/.gse-radio/channelList.json` so you won't loose it during reinstalls.

Thank you

I also tried the version from master repo. Still the same as on EGO

**Comment by junaru** [comment]
I was able to reproduce this but only with the default theme. Can you checkout and test
[junaru/gnome-shell-extension-radio/gnome-3.36-icon-style-class-fix ](/junaru/gnome-shell-extension-radio/tree/gnome-3.36-icon-style-class-fix) ?
Dont forget to `$ git checkout gnome-3.36-icon-style-class-fix` before `$ make install`

**Comment by Etamuk** [comment]
I am sorry, but my skills are not as big that I can follow your steps. Using `git` is to hard for me.

**Comment by junaru** [comment]
Well if you change your mind and want to try its as easy as
````
$ git clone https://github.com/junaru/gnome-shell-extension-radio.git gseradio
$ cd gseradio
$ git checkout gnome-3.36-icon-style-class-fix
$ make install
````

**Comment by hslbck** [comment]
@Etamuk I merged @junaru fixes to master. So you could give git a try. There are still more things broken with GNOME 3.36. This means a release on extension page for this version is at the moment not planned

**Comment by Etamuk** [comment]
Thank you! Also to @junaru. 
I installed the new version and the icons are fine now. It looks good for now. 
Yes, I know the other problems in combination with GNOME 3.36.
Kind regards
