### ISSUE TITLE
Invalid tags

### ISSUE THREAD

**Issue by Nikt-OS** [hslbck/gnome-shell-extension-radio#152]
![image](https://user-images.githubusercontent.com/24947331/82870589-e3f9b800-9f38-11ea-8ee2-5aae2f71692d.png)
changing encoding not help

**Comment by hslbck** [comment]
Couldn't reproduce issue when adding station from search, see 
![tags](https://user-images.githubusercontent.com/7780098/88711465-82142500-d118-11ea-96df-1ed5e3fea9b0.png)

No need to change any encoding on my side
