### ISSUE TITLE
Station list, channel addition, search don't work anymore

### ISSUE THREAD

**Issue by sisou** [hslbck/gnome-shell-extension-radio#153]
**Fedora 31 Workstation (Wayland), Gnome Shell 3.34.5**

I don't know since when, but on my desktop the buttons for the station list, channel adding and search don't work anymore. No `ModalDialog` opens when those buttons are clicked. The settings button still opens the settings window.

This was first reported by **ingli** on the Gnome Extensions page on May 3rd:
https://extensions.gnome.org/extension/836/internet-radio/

Gnome Looking Glass (`Alt+F2` -> `lg`) does not show any errors for the extension.

Extension version 13.

**Comment by hslbck** [comment]
Did you try removing and adding the extension again? For Gnome Shell 3.34 the modal dialog should work as expected, but didn't check Gnome 3.34.5 explicitly and I don't have it around anymore

**Comment by fbijma2** [comment]
Here the same. Installed on Fedora 32 and pulled from github, search is not working at all. Tried to put Café del Mar by hand and now it says missing plugin.

**Comment by Cyborgscode** [comment]
to add new channels for now edit ~/.gse-radio/channelList.json and reload the gnome-shell with ALT+F2 "r". 

Be aware, that those numbers are UUIDs.. do not reuse one.

**Comment by Cyborgscode** [comment]
@hslbck : i like that addon so much, i hate to see it not continued :(

**Comment by hslbck** [comment]
With latest development version all should work again, for GNOME 3.36 and GNOME 3.38
