### ISSUE TITLE
Problem with *.m3u8 radio stream

### ISSUE THREAD

**Issue by matog** [hslbck/gnome-shell-extension-radio#156]
I'm trying to add https://server1.stweb.tv/rcvos/live/playlist.m3u8 to the Radio Extension. But it gives a "No server stream audio find". The station is working properly on Rhythmbox. (Ubuntu 20.04)

**Comment by hslbck** [comment]
m3u8 file doesn't contain any http url. No stream address found, please check if you find a different link for this station
