### ISSUE TITLE
Does not work anymore with Gnome Shell 3.38.0

### ISSUE THREAD

**Issue by galen1423** [hslbck/gnome-shell-extension-radio#157]
Hi,

As mentioned in title, your extension fail to launch with G.S 3.38.0 :
 
`No JS module 'tweener' found in search path`

Thanx for this useful application. :)

**Comment by jens-st** [comment]
I can confirm that, I'm using Debian Sid.
GNOME Shell 3.38.0

**Comment by Radfahrer1964** [comment]
I can confirm that, too.
I am using Debian Testing with Gnome Shell 3.38.0

**Comment by Applejack01** [comment]
Ditto, My favourite extension by far, hope it's back soon

**Comment by enigma131** [comment]
Not working here too, Fedora 33 with gnome shell 3.38.1

**Comment by jschwender** [comment]
I can install it from most recent sources, it works in gnome-shell 3.38, but after a reboot the extension is wiped out.

**Comment by galen1423** [comment]
@jschwender 

Probably your system has a misfunction... with fix, extension works as expected and stil present at reboot. And happily ^^.
What OS are you using ?

**Comment by jschwender** [comment]
Ubuntu groovy (20.10), just upgraded.

**Comment by galen1423** [comment]
Strange... I am using Ubuntu 20.10 too and it works perfectly; About that, i am listening radio currently as i write these words.

When you wrote « wiped out », you mean that your extension folder named `radio@hslbck.gmail.com` disappear of $HOME/.local/share/gnome-shell/extensions directory ?
You are sure not to use a live cd/usb or usbkey O.S with non persistent partition ?

**Comment by jschwender** [comment]
Exactly, the complete folder radio@hslbck.gmail.com is gone after reboot. I have no idea why that could be caused from. It is an installed system, no live partition. After a make install in the source directory it s there, if i restart gnome-shell the icon appears and i can use it normally.

**Comment by jschwender** [comment]
gnome-shell-extension-prefs displays the extension as version 14, everything looks ok, until i reboot.

**Comment by hslbck** [comment]
Extension itself should work with GNOME 3.38. Extension itself cannot control if it gets removed or not

**Comment by jschwender** [comment]
Now i installed the extension globally,  which prevents it from disappearing. Works for me.
