### ISSUE TITLE
Error on installing on Fedora 33

### ISSUE THREAD

**Issue by enigma131** [hslbck/gnome-shell-extension-radio#163]
Installing via https://extensions.gnome.org/extension/836/internet-radio/ like for Fedor a32 (was working fine).
How to solve it ? (gnome shell 3.38.1 on Fedora 33 up to date linux 5.8.18-300)

**Comment by hslbck** [comment]
New version available on https://extensions.gnome.org for GNOME 3.36 and GNOME 3.38. Please update, extension should work afterwards

**Comment by enigma131** [comment]
Yes is working now thanks! I had to remove previous one, reboot computer and re-install. Normal upgrade via interface don't work.
