### ISSUE TITLE
Cannot see buttons when using light theme

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [hslbck/gnome-shell-extension-radio#164]
Pop!_OS 20.10
GNOME 3.38.1

Here is the appearance when using Dark Theme, which is fine:

![image](https://user-images.githubusercontent.com/5648989/99238435-a2640e80-27f1-11eb-8fb8-adf97247d12e.png)

However, I used Light Theme. Here is what that looks like:

![image](https://user-images.githubusercontent.com/5648989/99238627-dfc89c00-27f1-11eb-90a5-8ffc135c4306.png)

I can't make out any of the buttons.

**Comment by Applejack01** [comment]
Ditto, but great to have it working again. Thank you for great work.

**Comment by hslbck** [comment]
Style class system-menu-action no longer available in gnome-shell.css. Therefore it was replaced by radio-menu-action in this extension stylesheet.css. For now you have to overwrite the colors for it with color values from your light theme

**Comment by kacastorp** [comment]
How would I do that? Override the colors. Sorry for my ignorance

**Comment by Bananas-Are-Yellow** [comment]
This is what I did.
```
cd ~/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com
```
Then edit `stylesheet.css` and change `color` and `background-color` as follows:
```
.radio-menu-action {
  margin-left: 20px;
  /* color: #eeeeec; */
  color: #215d9c;
  border-radius: 32px;
  padding: 13px;
  border: 1px solid #282c2c; 
}

.radio-menu-action:hover, .radio-menu-action:focus {
    /* background-color: rgba(238, 238, 236, 0.1); */
    background-color: powderblue;
    /* color: #eeeeec; */
    color: #215d9c;
    border: none;
    padding: 14px; 
}
```
Hope this works for you.

**Comment by kacastorp** [comment]
Hi David,

your a genious, thanks a lot, works like a charm.

Cheers
Wolfgang
Am Mittwoch, dem 05.01.2022 um 09:17 -0800 schrieb David Taylor:

**Comment by hslbck** [comment]
Changed layout in f046e6d1802e873541d9ef4cb6f96b0c3fe737d5 which uses shell styles only again. Issue should be solved by it
