### ISSUE TITLE
Feature request: scheduler

### ISSUE THREAD

**Issue by antvrs** [hslbck/gnome-shell-extension-radio#166]

**Comment by antvrs** [comment]
I keep thinking how I'd like to regularly tune in to certain DJs/shows on various channels. Perhaps, one day, there could be some way to automate this? 
No issues, just an idea. Thanks for the excellent utility.
 -A

**Comment by hslbck** [comment]
Thanks for reporting the feature request. For me this feature is a bit out of scope of this minimal extension. I guess that you like to tunein to specific shows, what it be sufficient to create a custom calendar which notifies you about shows?
