### ISSUE TITLE
Error: Requiring GstPbutils on POP_OS 20.10 via FireFox or make install

### ISSUE THREAD

**Issue by prasket** [hslbck/gnome-shell-extension-radio#167]
Hello - I am trying to install this extension under POP_OS 20.10 (Ubuntu 20.10 based) and getting the following error in /var/log/syslog when installing via https://extensions.gnome.org/extension/836/internet-radio/ in Firefox. I also tried cloning repo and `make install` I could not see the error but did show a yellow ! in Gnome Tweaks. 

`JS ERROR: Extension radio@hslbck.gmail.com: Error: Requiring GstPbutils, version none: Typelib file for namespace 'GstPbutils' (any version) not found`

![gnome-ext-internetradio-error](https://user-images.githubusercontent.com/15177354/100291400-861f4a80-2f32-11eb-82cf-6fbc03e25336.png)

I also wonder if this issue is the same but user did not provide any more info. Issue #165

**Comment by hslbck** [comment]
Please check if gir1.2-gst-plugins-base-1.0 is installed, see https://github.com/hslbck/gnome-shell-extension-radio/issues/117#issuecomment-418646045

**Comment by szul** [comment]
@hslbck Can confirm that this resolved the exact same issue for me.
