### ISSUE TITLE
Cannot add https m3u8 stream 

### ISSUE THREAD

**Issue by blackjackshellac** [hslbck/gnome-shell-extension-radio#168]
I was attempting to add the URL for this stream,

`https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/master.m3u8`

but clicking the Add button does nothing with no apparent error.  I can play the url without problems with vlc so I know it works.  

If I change the protocol from https to http I can add the URL and it will play, so this did work.

`http://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/master.m3u8`

**Comment by blackjackshellac** [comment]
One interesting side note is that when editing the stream url, the extension displayed the current substream from master.m3u8 rather than the original url above,

```
$ cat master.m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=46000,CODECS="mp4a.40.2"
https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/index_48_a-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=46000,CODECS="mp4a.40.2"
https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/index_48_a-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=62000,CODECS="mp4a.40.2"
https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/index_64_a-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=62000,CODECS="mp4a.40.2"
https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/index_64_a-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=93000,CODECS="mp4a.40.2"
https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/index_96_a-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=93000,CODECS="mp4a.40.2"
https://cbcliveradio-lh.akamaihd.net/i/CBCR1_MTL@360544/index_96_a-b.m3u8?sd=10&rebase=on
```

attempting to play one of these streams also failed.
![Screenshot from 2020-12-01 07-38-37](https://user-images.githubusercontent.com/825403/100742225-724b6c80-33a8-11eb-8705-3f20380b0c83.png)

**Comment by hslbck** [comment]
Should be fixed with latest commit
