### ISSUE TITLE
Doesn't show properly align icons in the menu

### ISSUE THREAD

**Issue by prasadpatil25** [hslbck/gnome-shell-extension-radio#169]
I am using this radio extension on Fedora 33 update to date till today (gnome-session on Wayland).  Icons are not properly aligned as shown in this extension sample images.

![Screenshot from 2020-12-05 21-43-20](https://user-images.githubusercontent.com/12842912/101252431-2a2f9f80-3744-11eb-8e64-0b113e6aad9e.png)

Also, this extension shows an error as shown below:

![Screenshot from 2020-12-05 21-54-02](https://user-images.githubusercontent.com/12842912/101253831-91e5ea80-3744-11eb-89c6-e76754d54526.png)

**Comment by hslbck** [comment]
Which GNOME Shell version do you use? Latest supported version are 3.36 and 3.38 with extension version 14 from the extension page. Icons should work ok with version 14

**Comment by prasadpatil25** [comment]
These are details:

file:///home/prasadpatil/Pictures/Screenshot%20from%202021-01-06%2023-09-35.png

**Comment by hslbck** [comment]
Issue present again in GNOME 40

**Comment by hslbck** [comment]
Layout fixed for me with latest search provider commit

**Comment by hslbck** [comment]
Layout is working when there is no error reported by gjs
