### ISSUE TITLE
Show title notification in the panel without radio station name

### ISSUE THREAD

**Issue by matrixik** [hslbck/gnome-shell-extension-radio#171]
Hello, thank you for this nice radio player.

Could you add option to hide radio station name in the top panel so only song title is shown?

I have only one radio station I'm listening to and they have dance genre used at the beginning of song title ("Dance Passion", useful for learning dance) so for example: `Salsa - Ven Devorame Otra Vez - 85 bpm`. If radio station name was not displayed then it would be easier to spot it when next song start.

**Comment by junaru** [comment]
You could just replace https://github.com/hslbck/gnome-shell-extension-radio/blob/5b4d096b40c850b92d5ce19f544651c454738864/radio%40hslbck.gmail.com/titleMenu.js#L30
with:
` this._titleInfo.set_text(titleInfo); `

Just search for titleMenu.js on your system and edit the mentioned line.

**Comment by hslbck** [comment]
Maybe there will be an option in the future for this as editing every time is not convenient. But for the time being you could use the solution provided by @junaru

**Comment by hslbck** [comment]
removed channel name from panelbar completely

**Comment by matrixik** [comment]
Thank you for this fix (even that I will not see it for a long time, I'm personally sticking with Ubuntu LTS versions).
