### ISSUE TITLE
GNOME 40 issues

### ISSUE THREAD

**Issue by hslbck** [hslbck/gnome-shell-extension-radio#174]
- Icons not properly aligned: #169 
- Search provider logs errors

**Comment by junaru** [comment]
>     * Icons not properly aligned: #169
Looks ok to me.
![radio](https://user-images.githubusercontent.com/59161/114606932-95feb780-9ca4-11eb-88a3-29fdd8419acf.jpg)
Apparently GNOME changed a lot of classes when it comes to themes so most custom ones are still broken.

**Comment by hslbck** [comment]
Styles aren't applied when using default theme too.

![extension](https://user-images.githubusercontent.com/7780098/114610983-cfcdbf00-9ca0-11eb-8f75-500fec235bcc.png)

Still strange that it sometimes work :laughing: It could be that issue is already present since previous version and it just didn't happen for me

**Comment by junaru** [comment]
Very strange, my screenshot is also with the default theme.

**Comment by enigma131** [comment]
I'm under Gnome40 with ArchLinux. I've compiled + install the git without error, but gnome-extension list didn't find the extension, so I can't install it. How to solve it ?

**Comment by enigma131** [comment]
I have found. Packet glib2 was missing on my system

**Comment by hslbck** [comment]
Fix for search provider solved issue with broken layout for me

**Comment by hslbck** [comment]
On wayland icontheme is not working
- Solution posted on https://gjs.guide/extensions/upgrading/gnome-shell-40.html#custom-icon-theme with `let iconTheme = Gtk.IconTheme.get_for_display(Gdk.Display.get_default());` doesn't work. Message get_for_display is not a function
