### ISSUE TITLE
Correct URL not working

### ISSUE THREAD

**Issue by mariolinux** [hslbck/gnome-shell-extension-radio#176]
If a correct URL is accidentally entered with leading spaces it will not work. You could add a check for the entered url to trim initial spaces.

I simply add a line with _trim()_ to the function __getStreamAddress_ in the file [channelCreator.js](https://github.com/hslbck/gnome-shell-extension-radio/blob/master/radio%40hslbck.gmail.com/channelCreator.js)

```
    _getStreamAddress(input) {
        input = input.trim(); // MY FIX
        let regexp = /\.(m3u|m3u8|pls)/i;

        ...
```

**Comment by hslbck** [comment]
Yes trim should do it, I will add it in the future. Thanks for reporting

**Comment by hslbck** [comment]
It's not released yet :)

**Comment by hslbck** [comment]
Closing the issue as it will be available when next release is appoved on extensions.gnome.org
