### ISSUE TITLE
Upgrade to Gnome 41

### ISSUE THREAD

**Issue by marekmosiewicz** [hslbck/gnome-shell-extension-radio#179]
I upgraded to Fedora 35 Beta and there is no my favourite extension yet. I have checkout from GitHub updated shell version in meta config json file but radio do not show in bar.

**Comment by hslbck** [comment]
Can you maybe provide some log information with the error message. Otherwise I will check the extension again when Arch updates its packages to GNOME 41

**Comment by marekmosiewicz** [comment]
Still does not work.

**Comment by sam9032** [comment]
Works perfectly fine for me on Arch with Gnome 41. Thank you @Tamahome-M! :+1:

**Comment by hslbck** [comment]
Works for me on Arch as well. Created a new release and uploaded it on extensions.gnome.org as well. If review is passed it should be available in the next couple of days

**Comment by marekmosiewicz** [comment]
OK. I found reason it did not worked. In Fedora since 35 I think Gnome extensions are turned off by default. You need to install gnome-extensions-app and enable them: https://ask.fedoraproject.org/t/gnome-shell-extensions-not-working/13698
