### ISSUE TITLE
No search provider functionality in GNOME 41

### ISSUE THREAD

**Issue by didierm** [hslbck/gnome-shell-extension-radio#182]
# Setup
* **GNOME 41.1** (Fedora 35)
* gnome-shell-extension-radio **v18**
* Preference **[Enable as search provider for GNOME Shell]**  is enabled

# Issue
* when searching for a (sub)string of a radio station name in Gnome Shell, **no results** are returned

# Trace
* _(searchProvider.js)_ **enableProvider**() is called
* _(searchProvider.js)_ radioSearchProvider.**constructor**() is executed
* when typing a string in GNOME Shell, _(searchProvider.js)_ radioSearchProvider.**getInitialResultSet**() is never called.

# Additional info : 
* the v18 search provider works with GNOME 40.5 (Fedora 34)
* the search provider of the [ssh search provider](https://github.com/F-i-f/ssh-search-provider) extension, which also uses **Main.overview._overview.controls._searchController._searchResults._registerProvider** , works fine in GNOME 41.1

**Comment by didierm** [comment]
This issue appears to be fixed by wrapping (searchProvider.js) enableProvider() in a delayedRegistration loop.
(refence : https://github.com/F-i-f/ssh-search-provider/blob/32daf4d78138ce039253159174cbf05799acc939/src/extension.js#L543)

**searchProvider.js** : 
```

...
const MainLoop = imports.mainloop;
const Lang = imports.lang;
...
function enableProvider() {
    this._delayedRegistration = MainLoop.idle_add(Lang.bind(this, function() {
		if (!radioSearchProvider) {
			radioSearchProvider = new RadioSearchProvider();
			Main.overview._overview.controls._searchController._searchResults._registerProvider(radioSearchProvider);
		}
		this._delayedRegistration = null;
    }));
}
```
Note : function **disableProvider()** should be patched accordingly.

**Comment by hslbck** [comment]
Can you please make an example what you are searching for?
I checked both on Wayland and Xorg and search provider for station name works just fine for me on Arch with GNOME Shell 41.1 and extension version 18

**Comment by didierm** [comment]
1. The built-in search function for radio stations (https://www.radio-browser.info) works without issues (e.g. when searching with the string "**nws**", the radio station "**VRT NWS**" is found, and can be added to the extension's stations list), as expected.

2. With the station added, subsequently using the GNOME Shell search function (see screenshot below) and entering the same search string "**nws**", the station is not found, unless the abovementioned patch is applied.

![image](https://user-images.githubusercontent.com/989004/142729854-4775f74f-6afd-460c-8ac0-cc24e180b60d.png)

**Comment by hslbck** [comment]
Followed your steps as described above. Added VRT NWS from built in search to stations. Afterwards searched for it in overview and station was found as expected. No patch needed on my side

**Comment by didierm** [comment]
Thank you for taking the time to check this.
I will try to reproduce on a clean Fedora 35 installation and report back.

**Comment by didierm** [comment]
Note : I have next to none knowledge of Gnome Shell programming, but superficially looking at the patch, I'd (wildly) guess from the used terminology "delayedRegistration" and "MainLoop.idle", this may be an e.g. timing-dependent, and hence more difficult to reproduce issue ?
