### ISSUE TITLE
Use of media buttons not working consistently

### ISSUE THREAD

**Issue by kacastorp** [hslbck/gnome-shell-extension-radio#183]
I activated Play/Stop über Mediatasten. But this only worked once so far after disabeling the option and reenabeling it again. I tried the default allocation of the key board and then I allocatet the relevant Buttons to the relevant feature, but still not working. I am on Gnome-Shell 41 with Fedora 35.

**Comment by hslbck** [comment]
Could only reproduce behaviour when using Wayland. Using X mediakeys still work fine. But I found this [blog post](https://www.hadess.net/2021/10/psa-gnome-settings-daemons-mediakeys.html which ) which suggests to use mpris instead of settings daemon in the future. I guess some refactoring is required for the extension

**Comment by kacastorp** [comment]
Ok, thanks, that explains it, I am on wayland. But that's not a big prob

hslbck ***@***.***> schrieb am Mi., 12. Jan. 2022, 21:41:

**Comment by kacastorp** [comment]
Just checked again. There was a big update for Fedora 35 today,
including Pipewire packages. So far the media buttons work now on
Wayland.

Am Mittwoch, dem 12.01.2022 um 12:41 -0800 schrieb hslbck:

**Comment by kacastorp** [comment]
And now a follow up. Behaviour is not consistent. In both X-Session and Wayland the buttons work fine upon login. But if the session runs for a while and at the latest after suspend and wake up the buttons are non functional until restart of the session.

**Comment by kacastorp** [comment]
As of todays Fedora Update, all well. The buttons work consitently even after suspend.
