### ISSUE TITLE
Version 14 on Gnome 3.36 is broken

### ISSUE THREAD

**Issue by Ileca** [hslbck/gnome-shell-extension-radio#184]
Hello.
I am using the version 14 on Gnome 3.36 and this is what I am getting:
![Screenshot from 2022-02-03 02-45-31](https://user-images.githubusercontent.com/17970230/152267685-3a038596-2585-4e0c-a31b-afd4be9c4ae2.png)

Also, every radio gives me a stream error, even the one I added manually.

The menus appear to work, tho.

**Comment by Ileca** [comment]
Ok so I upgraded to Inpish and tried version 18. I couldn't load the extension because I didn't have GstPbutils. I solved this issue reading another issue here. Just want to say that if gir1.2-gst-plugins-base-1.0 is required, it should be added to the readme.
Anyway, still this stream error error. But when I added a radio and clicked ok, the extension froze my computer... fortunately, for some seconds.

**Comment by hslbck** [comment]
Not every distribution needs gir1.2-gst-plugins-base. So far this package is required for Debian / Ubuntu based distributions. The extension itself cannot install dependencies itself.

For buttons please have a look at https://github.com/hslbck/gnome-shell-extension-radio/issues/164. Currently for light theme the css of the extension has to be modified, as GNOME devs changed some styles a few release ago which were used by the extension
