### ISSUE TITLE
Long lists of stations don't scroll 

### ISSUE THREAD

**Issue by jruschme** [hslbck/gnome-shell-extension-radio#185]
I have a long list of stations which I copied over to my laptop which has a 1366x768 resolution screen. As a result, the list extends past the bottom of the screen and I also can not access the buttons at the bottom.

**Comment by hslbck** [comment]
Could be only supported when using submenu items. An early version of the extension did that, but this would require and extra click every time you want to change the station.

I don't plan to change the list. It is intended to only contain favourites which should also work for small resolutions. For longer list you could always access it in the modal dialog window

**Comment by antoniocorbi** [comment]
Hi!
I also have the same problem, I was thinking in a solution like extensions like, i.e., ArchLinux Update Indicator apply, it provides a 'scrollable' list of updates that can be completely collapsed on user needs.
Thanks for your work on this extension!

**Comment by blickers** [comment]
It's really a big problem if the chanel list is long.

Adding group function and sub-menu is essential. #198

**Comment by blickers** [comment]
It's really a big problem if the chanel list is long.

Adding group function and sub-menu is essential. #198
