### ISSUE TITLE
Support Gnome 42

### ISSUE THREAD

**Issue by quinzee33** [hslbck/gnome-shell-extension-radio#186]
Currently on the Pop OS 22.04 beta with Gnome 42 and this extension isn't supported yet. Love the extension and would be happy to see it supported whenever you can get around to it. Thanks!

**Comment by coxackie** [comment]
indeed, adding 42 to metadata works, but it would be good for users if this was pushed in the repo instead of having to do it manually.

**Comment by hslbck** [comment]
Updated metadata and uploaded it to extensions.gnome.org
