### ISSUE TITLE
General question : Radio mirroring

### ISSUE THREAD

**Issue by marekmosiewicz** [hslbck/gnome-shell-extension-radio#189]
I started to use internet radio about three years ago. From some time it brings me question about server mirroring. I frequently listen e.g Radio Paradise which is located in U.S I think. I do not know about radios internet connection but I think it is challenging to have e.g. 100000 concurrent listeners. Radio is HTTP stream. HTTP can provide redirect operation. I can imagine that my radio redirect me to some mirror. That is general question not related to gnome-shell-extension-radio.

**Comment by hslbck** [comment]
How did you import the radio station and how does your http url look like. I saw that some use some mirroring links.
