### ISSUE TITLE
Long favourites list exceeds screen 

### ISSUE THREAD

**Issue by antoniocorbi** [hslbck/gnome-shell-extension-radio#190]
Hi,

The extension works flawlessly for me except for not using a scrolled list for the favourites.

On my laptop small screen it quickly exceeds screen height and I can't see the controls nor the volume knob.

**Comment by hslbck** [comment]
Hi, 
please have a look at the explanation here https://github.com/hslbck/gnome-shell-extension-radio/issues/185. I won't change current list behaviour

**Comment by antoniocorbi** [comment]
Hi,
I was thinking in a solution like extensions like, i.e., ArchLinux Update Indicator apply, it provides a 'scrollable' list of updates that can be completely collapsed on user needs.
Thanks for your work on this extension!

**Comment by hslbck** [comment]
Yes I think this extension used a popup submenu entry as well, which would require an extra click to switch stations
