### ISSUE TITLE
Gnome 43

### ISSUE THREAD

**Issue by galen1423** [hslbck/gnome-shell-extension-radio#191]
Hello,

I'm testing version Ubuntu 22.10 (development branch) with Gnome Shell 43 and since radio extension do not work anymore and return the following error : 
`Soup.SessionSync is not a constructor`

Many thanks for this essential.

**Comment by jmrbachiller** [comment]
Same problem in Debian Unstable with GNOME 4.3.
Thanks for all the work.

**Comment by palWorx** [comment]
There is another extension that seems to have the same problem:
https://gitlab.com/skrewball/openweather/-/issues/48

Seems to be a libsoup3 issue.

**Comment by palWorx** [comment]
On 23 Jul was an issue opened, but to this day without any reaction from the developer. On 8 Apr was the last solved issue.

So it looks like gnome-shell-extension isn't actively maintained anymore.

**Comment by jmrbachiller** [comment]
Thanks for the tip on libsoup3. It's easy to solve this issue:

1) Edit
/home/mane/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/channelCreator.js

2) Change line 19
// import to get m3u, pls files
const Soup = imports.gi.Soup;
const _httpSession = new Soup.SessionSync();

to this:
// import to get m3u, pls files
const Soup = imports.gi.Soup;
const _httpSession = new Soup.Session();

Restart gnome-shell and voilá!
Hope it works for you.

(I'll try to solve openweather issue; I use this extension too)

**Comment by palWorx** [comment]
@jmrbachiller 
That worked perfectly, you absolutely made my day! Thank you so much!
If you get the openweather extension running, could you notify me?

**Comment by galen1423** [comment]
Nice! It working at new! :+1:

**Comment by jmrbachiller** [comment]
@palWorx
If found a workaround, I'll notify in https://gitlab.com/skrewball/openweather/-/issues.
I'm glad it works! ;)

**Comment by palWorx** [comment]
Thank you again, I appreciate your work!

**Comment by hslbck** [comment]
A fix is prepared by @marekmosiewicz and will be merged once I could verify it

**Comment by kacastorp** [comment]
Any news as to when the update will be released for Gnome 43. Had a shock after I updated to Fedora 37 today and my radio was gone.

**Comment by bwakkie** [comment]
Super! Have back my radio on Manjaro

**Comment by kacastorp** [comment]
Changing the gnome version it works for me too, almost. Still search of new stations is not working.

**Comment by henriktorget** [comment]
I love this radio, please upgrade.

**Comment by hslbck** [comment]
Merged pull request #192. Playing radio stations should work with it, but styles for managing station list and search are broken. More changes required for that

**Comment by hslbck** [comment]
Update to GNOME 43 in f046e6d1802e873541d9ef4cb6f96b0c3fe737d5
