### ISSUE TITLE
Radio Description use and overwrite all windows 

### ISSUE THREAD

**Issue by XUTOS83** [hslbck/gnome-shell-extension-radio#196]
Radio Description use and overwrite all windows, eventually occupy all screen and cannot use the extension buttons or stop it without media buttons  

![Screenshot from 2023-02-02 23-30-14](https://user-images.githubusercontent.com/37241031/216474970-66e46c87-281b-49d7-a8f8-1e5b3b2ff630.png)
![Screenshot from 2023-02-02 23-33-34](https://user-images.githubusercontent.com/37241031/216474973-fc63cd3f-137c-4e0a-a252-3d17c58ce34b.png)

**Comment by hslbck** [comment]
Which version of the extension do you use. For longer titles line breaks were introduced in https://github.com/hslbck/gnome-shell-extension-radio/issues/38 which solved quite some time already
