### ISSUE TITLE
Buttons not visible with light desktop theme

### ISSUE THREAD

**Issue by kev005** [hslbck/gnome-shell-extension-radio#197]
Please see the attached screenshot where using the Gnome light theme causes the buttons to be very hard to see.
![Screenshot from 2023-03-02 12-07-35](https://user-images.githubusercontent.com/52118709/222516975-c6b5d8b9-0a32-4274-9796-2bdbc0bb8160.png)

**Comment by hslbck** [comment]
Fix for older versions describe here https://github.com/hslbck/gnome-shell-extension-radio/issues/164. For the latest extension version issues does not exist anymore as button layout was changed
