### ISSUE TITLE
Grouped sub-menu needed for big chanel list.

### ISSUE THREAD

**Issue by blickers** [hslbck/gnome-shell-extension-radio#198]
[channelList.zip](https://github.com/hslbck/gnome-shell-extension-radio/files/10906238/channelList.zip)

Here is an example of big chanel list containing more than 60 radio stations. Without submenu, lots of stations won't be displayed on the screen (resolution <=1920x1080) because the menu list is too long. If we can put these Chanels in groups with names like UK, Ireland, Australia, Canada,...... and make each group a sub-menu, the problem will be solved.

**Comment by hslbck** [comment]
Same issue as other issues. Will keep #194 open to address it
