### ISSUE TITLE
Support Multimedia Keys

### ISSUE THREAD

**Issue by lightonflux** [hslbck/gnome-shell-extension-radio#20]
It would be nice if the play and pause key etc, just like Rhythmbox. 

* XF86AudioPlay
* XF86AudioPause 
* XF86AudioStop

**Comment by hslbck** [comment]
Maybe I have a look into when I got some and make this an optional setting. Thanks for the feedback

**Comment by hslbck** [comment]
Implemented for play and stop keys with last commit. Disabled by default! Could be enabled in the extensions.js file by setting the value for "useMediaPlayerKeys" to true.
There a plans to implement a preferences window in the future for options like this

**Comment by hslbck** [comment]
with the latest commit it can be configured through a settings window
