### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by grg3** [hslbck/gnome-shell-extension-radio#204]
Gnome 45 is upon us and I hope you will be able to do a 45 version of this extension. It is my favorite extension!
Thanks again!

**Comment by hslbck** [comment]
When Archlinux has updated their GNOME packages I will look into updating the extension to GNOME 45. Reading from https://gjs.guide/extensions/upgrading/gnome-shell-45.html there seem to be quite some changes needed for the extension to support version 45

**Comment by enecciari** [comment]
Hi, in my branch https://github.com/enecciari/gnome-shell-extension-radio/tree/45  i have an update version that work for gnome-45.

It is necessary maintain to different release one that works with gnome-45 and another that is compatible with older versions of gnome.

**Comment by fewaltix** [comment]
https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

There's also this helpful link for potential extension devs/contributors. If anyone gets stuck or needs a little help, the Gnome devs on their [Discourse](https://discourse.gnome.org/tag/extensions) and [Matrix](https://matrix.to/#/#extensions:gnome.org) channels are around to offer whatever help they may be able to provide. 

Thanks for the great extension!

**Comment by MarcMichalsky** [comment]
I can confirm that @enecciari's [branch](https://github.com/enecciari/gnome-shell-extension-radio/tree/45) works.

**Comment by tagirb** [comment]
> I can confirm that @enecciari's [branch](https://github.com/enecciari/gnome-shell-extension-radio/tree/45) works.

+1

**Comment by keithy999** [comment]
Brilliant. Missed this so much. Thank you @enecciari

**Comment by hslbck** [comment]
Thank you @enecciari. Merged your changes for version 45 and put it up for review on extension.gnome.org
