### ISSUE TITLE
Solution for gnome-shell-extension-radio Start-up Error on Arch Linux

### ISSUE THREAD

**Issue by einhop** [hslbck/gnome-shell-extension-radio#206]
Hello everyone,

I've noticed some discussions around issues with the gnome-shell-extension-radio, particularly regarding a start-up error. I wanted to share my experience and solution, hoping it might assist others, especially those on Arch Linux or similar distributions.

### **Issue Description:**
The gnome-shell-extension-radio would not initialize correctly, showing an error related to the gschemas.compiled file.

### **Environment:**
OS: Arch Linux
GNOME Shell Version: 45.4
Extension Version: 23

### **Steps to Reproduce:**
Install the gnome-shell-extension-radio.
Attempt to start the extension.
Observed Error:
`GLib.FileError: Failed to open file “/home/username/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory`

### **Solution:**
Here's a step-by-step guide to resolve the issue:

Install Necessary GStreamer Plugins:
These plugins are essential for the extension's functionality.
`sudo pacman -S gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly`

Clone the Extension Repository:
`git clone https://github.com/hslbck/gnome-shell-extension-radio`

Copy the Extension to the GNOME Shell Extensions Directory:
`cp -r gnome-shell-extension-radio/radio@hslbck.gmail.com ~/.local/share/gnome-shell/extensions/`

Compile GSettings Schemas Manually:
Navigate to the schema directory and compile the schemas.
`cd ~/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/schemas`
`glib-compile-schemas .`

After completing these steps, the gnome-shell-extension-radio started working as expected on my system.

Although I've outlined the process for Arch Linux, the general approach may be applicable to other Linux distributions with some modifications.

Hope this helps, and I'd love to hear if this solution works for you or if there are any further issues or improvements to be made.

Best regards,
ein

**Comment by hslbck** [comment]
@einhop Thanks for your documenting this

**Comment by wbob** [comment]
would you agree to include this in the build.sh or is it host system dependant? running GNOME 46 myself.

 ```diff
 diff --git a/build.sh b/build.sh
old mode 100644
new mode 100755
index c7af442..6414f31
--- a/build.sh
+++ b/build.sh
@@ -10,6 +10,8 @@
 
 
 set -e
+echo "compile gschemas ..."
+glib-compile-schemas "radio@hslbck.gmail.com/schemas/"
 
 echo "Packing extension ..."
 gnome-extensions pack radio@hslbck.gmail.com \
@@ -24,7 +26,8 @@ gnome-extensions pack radio@hslbck.gmail.com \
    --extra-source="searchDialog.js" \
    --extra-source="searchProvider.js" \
    --extra-source="titleMenu.js" \
-   --extra-source="../COPYING" 
+   --extra-source="../COPYING" \
+   --schema="schemas/gschemas.compiled"
    
 echo "Packing done!"
```
