### ISSUE TITLE
use open source radio directory

### ISSUE THREAD

**Issue by segler-alex** [hslbck/gnome-shell-extension-radio#23]
Thank you for your cool app!!
maybe you could use the radio directory at:
http://www.radio-browser.info

it is completely open source and has a nice xml/json api

greetings from vienna
alex

**Comment by hslbck** [comment]
Hi Alex,

I will have a look at it, as using directories get requested more often. But as always don't expect an implementation to soon ;)

**Comment by hslbck** [comment]
added a search option  for your directory.

BR
