### ISSUE TITLE
Favourite channel temporarily disappears from favourite list

### ISSUE THREAD

**Issue by nielsrune** [hslbck/gnome-shell-extension-radio#24]
If a stream address is changed for a favourite channel, but the channel name is not, the channel disappears from the favourite list until the shell is restarted.

It seems, that the _removeFromFavourites function is run twice in this situation when old and new channel has the same name, but that said function cannot differ between oldChannel and newChannel. Thus, the oldChannel is removed from favourites, the newChannel is added, and the newChannel is removed again from the second run of _removeFromFavourites(oldChannel)

I have tried a few things, but can't just figure out a working, yet stateful, solution at the moment.

**Comment by hslbck** [comment]
ran into the same issue once. I'll have look at it

**Comment by hslbck** [comment]
fixed with latest commit. The method "_removeFromFavourites" was indeed called twice. There was one explicit call and one call in the _deleteChannel method. Removed the explicit call
