### ISSUE TITLE
Issue with play button

### ISSUE THREAD

**Issue by hispagnu** [hslbck/gnome-shell-extension-radio#27]
Hello, i have a problem with play button in this extension, when i play the music sound if and i click again "stop" but when i repeat a few times "play" -> "stop" and "play"->"stop" etc... the system freeze a few seconds, the more times I give longer hang on every click. I use now manjaro and the gstreamer versión is "gstreamer-1.8.2-1" i use others extensions: dash-to-dock, openweather, removable drive menu, user themes and volume mixer.

Thanks.

**Comment by hslbck** [comment]
Hi,
ok I can reproduce some slow down when clicking a lot on the play and stop button. However using middle click on the icon seems not be affected by this. Maybe some signals aren't disconnected properly. 
I will have a look at it.

**Comment by hispagnu** [comment]
I try with middle button and works fine, anyway i wait the fix, thanks.

**Comment by hslbck** [comment]
should be fixed with mentioned commit
