### ISSUE TITLE
Call AddChannelDialog._getStreamAddress() when clicking on a favourite item

### ISSUE THREAD

**Issue by pulb** [hslbck/gnome-shell-extension-radio#3]
Currently _getStreamAddress() is called when the user adds a new channel, so only one single streaming server is stored in the channel file and alternative streaming servers are removed. A better solution would be to store the m3u address in the channelist file and call _getStreamAddress()  if the user clicks on a favourite item, so there are alternative servers to choose from if a server is offline for some reason.

Apart from this, there should be `break` in the for loop of _getStreamAddress() if a http address has been found, so the first server is selected instead of the last one (the first server has a higher priority and may have better streaming quality).

**Comment by hslbck** [comment]
Added a break in the loop.
For now remaining with the solution of calling _getStreamAddress() once
