### ISSUE TITLE
how i can increase cache of stream?

### ISSUE THREAD

**Issue by petrowmaxic** [hslbck/gnome-shell-extension-radio#35]
the stream sometimes stops. how can I increase the buffering time of the stream (2 seconds at least)?

**Comment by hslbck** [comment]
Hi,

I didn't set a specific buffering time of the stream. I use the default setup of the gstreamer framework. I have to look into gstreamer if there is a setting for it.

Is this issue radio station specific?

**Comment by petrowmaxic** [comment]
hi, no, all stations have this error. I think that's my provider. sorry to change the provider I will not be able - territorial feature of not permitting - I live in the far North. in this case, could you tell me where can I see the manual for the configuration of gstreamer?

**Comment by hslbck** [comment]
ok, I had a look at the docs and playbin is handling buffering automatically. 

But there is a property 'buffer-size' which you could try out.
To do so add following line to the `setup()` function in `player.js`
```js
source.set_property("buffer-size", 512000);
```

complete function block:
```js
function setup(){    
    source = Gst.ElementFactory.make("playbin", "source");    
    source.set_property("uri", currentChannel.getUri());    
    source.set_property("buffer-size", 512000);    
    pipeline.add(source);    
    readTags();    
}
```

If this is not going to work, buffering messages need to be handled. But even with such a change I can't guarantee that streams are buffered properly for you.

**Comment by petrowmaxic** [comment]
your method didn't work, but you gave me an idea, when i can see, thank you.
