### ISSUE TITLE
[Feature request] Limiting the size of the current artist/title

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#38]
Hi,

I just noticed that sometimes, the size of the current artist/title is really big. Especially with radio dedicated to classical music...

E.g. :

![capture du 2016-12-08 18-14-38](https://cloud.githubusercontent.com/assets/16472988/21019918/9efdf118-bd72-11e6-8dba-82be15fdff9b.png)

And sometimes it's even worse...

It would be great to limit the maximum size displayed and to use some kind of auto scroll so the whole title/artist is still here if needed.

(I don't know what happens if the size is > to the screen size, I'll try to catch one like this !)

**Comment by hslbck** [comment]
Hi,

thanks for reporting. I never ran into such large title messages and you're right the displayed size should be limited. I'll have a look into it.

**Comment by hslbck** [comment]
Hi,

with the latest commit a fixed size for title and artist will be used. If the title is longer line breaks will be added.

**Comment by zapashcanon** [comment]
Works perfectly, thanks !
