### ISSUE TITLE
Feature Request: Survive Locksreen Mode

### ISSUE THREAD

**Issue by pulb** [hslbck/gnome-shell-extension-radio#4]
Everytime GNOMEs lockscreen kicks in the extension is disabled and thus streaming is aborted. This is very annoying and a big disadvantage compared to other streaming applets like radiotray. 

I'd suggest to just remove the indicator icon from the panel instead of disabling the extension if the lock screen triggers. An example how to achieve this can be found [here](https://github.com/pulb/mailnag-gnome-shell/blob/master/extension.js) @ line 384.

**Comment by morealaz** [comment]
This is really annoying. could you please fix it!!

**Comment by hslbck** [comment]
Extensions get removed on lock screen. I have to come up with some workaround. Currently I have not a lot of time to work on the extension

**Comment by coxackie** [comment]
Just writing to simply reiterate how cool it would be if this feature was implemented. It it the only thing right now that prevents a perfect experience. Thank you so much for your work and effort - this is a brilliant extension.

**Comment by gayanch** [comment]
`xset dpms force off` to the rescue!

**Comment by hslbck** [comment]
Possible solution discussed in https://github.com/hslbck/gnome-shell-extension-radio/issues/187
