### ISSUE TITLE
Contributors and copyright informations missing

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#43]
Hi,

I'm packaging this extension for Debian, I now have a working package, but I'm just missing a few informations to put in the `copyright` file.

Here's [the current version](https://gist.github.com/zapashcanon/53d8fb8694b56ac145fb05ea3fe8a4eb).

I'd like to ask to each contributor if informations given here are corrects, especially the name/pseudo + email. If you don't want to provide an email, just tell me.

Files + licenses should be correct - but if someone is willing to check the whole git history one more time, go for it. :)

As an example, for me it's:
```
Léo Andrès <leo@ndrs.fr>
```

- [x] @hslbck: it would be great if you could provide some contact email as you're the author of the extension...
```
hslbck <hslbck@gmail.com>
```

- [x] @stmc 
```
Stas Solovey <whats_up@tut.by>
```

- [x] @pkomur 
```
Piotr Komur <pkomur@gmail.com>
```

- [x] @urbalazs 
```
Balázs Úr <urbalazs@gmail.com>
```

- [x] @nielsrune
```
Niels Rune Brandt <nielsrune@hotmail.com>
```

- [x] @thony8 
```
Anthony Chaput <thonyc4@openmailbox.org>
```

- [x] @Bridouz 
```
Berthault Justin <justin.berthault@zaclys.net>
```

- [x] @narzb
```
Quentin Daem <quentin.daem@gmail.com>
```

- [x] @marjinal1st 
```
Ahmet Sezgin Duran <marjinalist1@gmail.com>
```

- [ ] @gmg137 
```
gmg137 <gmg137@live.com>
```

- [x] @X4lldux 
```
x4lldux <x4lldux@vectron.io>
```

- [x] @bezcitu 
```
bezcitu <secitem@tuta.io>
```

**Comment by stmc** [comment]
information about me is correct

**Comment by nielsrune** [comment]
Niels Rune Brandt <nielsrune@hotmail.com> for me :-)

**Comment by thony8** [comment]
And for me : Anthony Chaput thonyc4@openmailbox.org

**Comment by pkomur** [comment]
Hi,
Information about me is correct.

Piotr Komur
(pkomur@gmail.com)

28 gru 2016 4:40 AM "Léo Andrès" <notifications@github.com> napisał(a):

**Comment by urbalazs** [comment]
Information about me is correct.

**Comment by Bridouz** [comment]
For me informations are : 

Berthault Justin

justin[dot]berthault(at)zaclys[dot]net

**Comment by hslbck** [comment]
my email: hslbck@gmail.com

**Comment by marjinal1st** [comment]
My information is correct 👍

**Comment by hslbck** [comment]
I think X4lldux is missing on your list

**Comment by zapashcanon** [comment]
Oh, yes, indeed ! Thanks for spotting this.

There's only 11 contributors listed [here](https://github.com/hslbck/gnome-shell-extension-radio/graphs/contributors), I checked that I listed 11 here, but as narzb is not listed in the contributor list (no github account linked to his commit at the time) I didn't spotted one was missing... :/

So @X4lldux, could you confirm everything is correct ? :)

**Comment by X4lldux** [comment]
looks good 👍

**Comment by zapashcanon** [comment]
Just for the record, @narzb replied to me via mail. :)

**Comment by hslbck** [comment]
@zapashcanon Are you still waiting for gmg137 to reply? Otherwise you could just remove the chinese translations, if it's stopping you from packaging the extension

**Comment by zapashcanon** [comment]
No, it's not stopping from packaging, I've got his GitHub pseudo + mail, should be enough. I'm just a little busy atm. :/ I pushed a few commits on my fork, nothing's ready for a PR, I should be able to do it in two weeks (and finish it I hope).

**Comment by bezcitu** [comment]
@zapashcanon 
for bezcitu: secitem@tuta.io

**Comment by zapashcanon** [comment]
Thanks ! :)

**Comment by zapashcanon** [comment]
Looks like it won't be a problem for @gmg137 as I've got pseudo + mail.

Thanks to all of you. :)
