### ISSUE TITLE
New tag ?

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#44]
Hi,

@hslbck, could you please tag a new version once #41 is merged ? So that I'll be able to propose a first Debian package using this release.

Thanks. :)

**Comment by hslbck** [comment]
Hi,

merged pull request #41 and created the tag [1.4](https://github.com/hslbck/gnome-shell-extension-radio/releases/tag/v1.4).

**Comment by zapashcanon** [comment]
Thanks. :)
