### ISSUE TITLE
Copyright for convertCharset.js

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#53]
Hi,

In `convertCharset.js` there's a link to the source of the code, but it's in Russian, which I don't understand.

@nielsrune, if you do understand Russian, could you try to find which license is this code published under ? And, author + mail would be amazing.

Also, should I add you as a copyright holder for this file ?

**Comment by nielsrune** [comment]
Hi @zapashcanon 
As I understand it, the site xpoint.ru from where I got the conversion structure, is mainly a programming message board.
Also, there is a knowledge base section. The knowledge base seems more or less abandoned. According to the front page the most recent change in the knowledge base was on 25-02-2011.

The [url](http://xpoint.ru/know-how/JavaScript/PoleznyieFunktsii?38#PerekodirovkaIzWindows1251IKOI) I mentioned in `convertCharset.js` is a sub page in this knowledge base under `Javascript` called Useful functions. It appears from the page's change log ([история](http://xpoint.ru/know-how/JavaScript/PoleznyieFunktsii?history)-link at the bottom) that the section with the charset conversion functions was added on 19-08-2005 by some Давид Мзареулян with would transcribe to David Mzareulyan. He is registered with e-mail `david@hiero.ru`, cfr. [http://xpoint.ru/user/107](http://xpoint.ru/user/107).

I have not been able to find anything regarding license. I wonder if it would be to bold to assume public domain when a copyrights are not claimed?

For the win1251 and koi8-r functions I have just made neccesary adjustments for the Internet Radio extension, so in this matter, and in lack of better knowledge, credits belongs to David Mzareulyan.
I have added support for koi8-u. (Support for additional charsets is on my planned to do list).

**Comment by zapashcanon** [comment]
> David Mzareulyan

I'll try to contact him by mail to know about the license.

> I wonder if it would be to bold to assume public domain when a copyrights are not claimed?

I don't know, but I don't think it'll be accepted for the Debian packaging... :/ Will ask about this.

Anyway, thanks a lot for this !

**Comment by zapashcanon** [comment]
I've been able to contact David Mzareulyan and he agreed on publishing his code under the Expat (MIT) license. I've just opened a PR to add this in the file and added you as a copyright holder. Thanks a lot for the help. :)
