### ISSUE TITLE
Getting "Stream Error"

### ISSUE THREAD

**Issue by wksantiago** [hslbck/gnome-shell-extension-radio#64]
Getting "Stream Error"  when trying to play radio music.

If I go to Chrome or Firefox and paste the URL the music plays with no problem.
OS:
Linux wks-pc 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

uname --version
uname (GNU coreutils) 8.26
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
gnome-shell --version

GNOME Shell 3.24.1

Hope there is help.

**Comment by hslbck** [comment]
Is the gstreamer framework as dependency installed? You can check this in the terminal via `dpkg --get-selections | grep gstreamer`

If this doesn't help, can you provide the url / station you want to add? Maybe there is a link to a  `.m3u` or `.pls` file

**Comment by wksantiago** [comment]
~$ dpkg --get-selections | grep gstreamer
gir1.2-gstreamer-1.0				install
gstreamer1.0-alsa:amd64				install
gstreamer1.0-clutter-3.0			install
gstreamer1.0-nice:amd64				install
gstreamer1.0-plugins-base:amd64			install
gstreamer1.0-plugins-base-apps			install
gstreamer1.0-plugins-good:amd64			install
gstreamer1.0-pulseaudio:amd64			install
gstreamer1.0-tools				install
gstreamer1.0-x:amd64				install
libgstreamer-plugins-base1.0-0:amd64		install
libgstreamer-plugins-good1.0-0:amd64		install
libgstreamer1.0-0:amd64				install
libreoffice-avmedia-backend-gstreamer		install


Here is one stream:
http://217.75.92.14:8000/nr160kb
Here is another one:
http://radioone.ice.infomaniak.ch/radioone-96.mp3

All links give the same error.

**Comment by hslbck** [comment]
ok, both streams work on my machine. I think the gstreamer plugin for mp3 support is missing. Install 
the package `gstreamer1.0-plugins-ugly` and try again.
If this doesn't help try the package `gstreamer1.0-plugins-bad`

**Comment by wksantiago** [comment]
@hslbck Installed both packages and at first it did not work so decided to restart host and then it worked.
Thanks,

**Comment by JMans15** [comment]
Hello, I got the same error on Pop!_OS with gstreamer1.0-plugins-ugly and gstreamer1.0-plugins-bad already installed and up to date, here's the URL to the stream I want to play: https://www.static.rtbf.be/radio/classic21/m3u/
The streams plays without any problem on Firefox
Thank you in advance for your answer
![Capture d’écran de 2020-04-17 20-02-47](https://user-images.githubusercontent.com/33575924/79600298-38627a00-80e7-11ea-88ce-56180fd10d44.png)
![Capture d’écran de 2020-04-17 20-02-23](https://user-images.githubusercontent.com/33575924/79600305-3d272e00-80e7-11ea-87e9-da870db3941d.png)
![Capture d’écran de 2020-04-17 20-01-50](https://user-images.githubusercontent.com/33575924/79600320-431d0f00-80e7-11ea-949e-b9f81383c410.png)

**Comment by hslbck** [comment]
@JMans15 Related to #147? If not please open a new issue
