### ISSUE TITLE
Can't remove a station

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#66]
Hi,

The easy way to reproduce is the following:

- search for "vivaldi", you should see two result `Radio Clasic Vivaldi` and `Calm Radio Vivaldi`
- click on the stars of the two stations, then click on one of them, click the "add" button
- you'll see the two stations in the favorites, but when you click on the button to manage stations, you'll see only one of them (the one on which you clicked before clicking on `add`)

Thus, I can't remove the other one.

**Comment by hslbck** [comment]
Hi,

I see the click on the star icon adds the channel as favourite but not to the channellist itself. The way it was intended to work was to add the highlighted channel only and not multiple channels at once.
For now when you reload the extension the channel which wasn't highlighted on add will be removed.

I'll check this and thanks for reporting.

**Comment by zapashcanon** [comment]
> when you reload the extension the channel which wasn't highlighted on add will be removed

That's true, I didn't noticed this. Thanks.

**Comment by hslbck** [comment]
should be solved by the latest commit. Only selected channel will be added to the favourites list

**Comment by zapashcanon** [comment]
Thanks.
