### ISSUE TITLE
Using XDG Base Directory Specification

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#67]
Hi,

Instead of saving the list of channels in `~/.gse-radio/channelList.json` it would be better to store it in the correct place according to the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

That is:

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

So, in `$XDG_DATA_HOME/gse-radio/channelList.json`, or, if `$XDG_DATA_HOME` is not set, in `$HOME/.local/share/gse-radio/channelList.json`.

Moreover, I think the folder `gse-radio` should be renamed to something like `gnome-shell-extension-radio` or the like, it wasn't trivial to find it, had to look at the source code, because nothing showed up when I searched for the extension name. :)

Thanks.

EDIT: maybe the last played radio could be moved to another place ? so, the main file is not edited each time (it would be useful in case where someone, like me, wants to sync the main file between many computers)

**Comment by hslbck** [comment]
Hi,

`$XDG_DATA_HOME` is probably the better location for the file and renaming the folder could also make sense. But there has to be some sort of transition, where the old folder is copied to the new location and afterwards deleted, otherwise there will be a lot of comments about lost channel configurations. 

About the last played radio station, I'll check what could be a proper solution here.

**Comment by coxackie** [comment]
I think it is high time to make this change - having a lot of dot files at the home directory is a bit of obsolete. I personally thing that `$XDG_CONFIG_HOME` (usually `$HOME/.config/`) would be a more appropriate place to place `gse-radio/channelList.json`.

**Comment by hslbck** [comment]
Did not do any investigation in this topic yet. Regarding directory without having checked definitions, only judging by name,  $XDG_DATA_HOME seems to fit, as it actually doesn't contain any config. Config of the extension is done in preferences instead
