### ISSUE TITLE
Deleting a channel shouldn't close window

### ISSUE THREAD

**Issue by pkkid** [hslbck/gnome-shell-extension-radio#70]
It's an odd workflow. -- When trying to delete a few stations I had to keep opening the channels list because it was closing each time I deleted one.

**Comment by hslbck** [comment]
I'll check the effort here, too. 
For now, if you want to edit or delete multiple channels at once, you can do this by editing the channellists.json file in ~/.gse-radio directory

**Comment by hslbck** [comment]
done in latest commit
