### ISSUE TITLE
Channels menu item should be a button

### ISSUE THREAD

**Issue by pkkid** [hslbck/gnome-shell-extension-radio#71]
This was another odd workflow to me. The menu items feel like they should work in the menu while the buttons (which are all grouped together) all open new windows. It feels a bit out of context to have the channels menu item open a window.

On a related note: if you do decide to make Channels a button, it would also be nice to not have to expand the favorites list. Consider making it the main list in the dropdown.

_I understand this bug could be considered personal preference, so feel free to tell me to bugger off._

**Comment by pkkid** [comment]
Woah. Did you just update the extension on gnome.org today? Half this stuff is already implemented. Sorry for the noise.

**Comment by hslbck** [comment]
i updated the extension on gnome.org last week. The changes itself are older, but were only on github before
