### ISSUE TITLE
Editing a channel should send you back to channel list

### ISSUE THREAD

**Issue by pkkid** [hslbck/gnome-shell-extension-radio#72]
The only way to get to the edit channel window is to go through the channels list. You should drop the user back at the channels list when editing a channel. Related: The button on the edit channel window is odd as it says "Add" when it should be something more along the lines of "Save".

**Comment by hslbck** [comment]
I'll check how much effort it is too change the workflow. And yes the button label should be different on edit. "Add" makes no sense here.

**Comment by hslbck** [comment]
Changed the behaviour in latest commit
