### ISSUE TITLE
Radio with same name

### ISSUE THREAD

**Issue by ozzymanborn** [hslbck/gnome-shell-extension-radio#77]
In radio-browser.info there are some same name stations even they're different city/country & in your extension search is hard with this kind of stations. Can you add more search options (like search can read tags details or at least read country info of the station)
I can always use Gradio but your app is very easy to use and I prefer yours.
Thanks.

**Comment by hslbck** [comment]
Thanks for your feedback. I'll check this when I've got some spare time and the current bugs are fixed 😄

**Comment by hslbck** [comment]
Added codec and bitrate as additional info in f046e6d1802e873541d9ef4cb6f96b0c3fe737d5
