### ISSUE TITLE
Multimedia Keys not work in Gnome 3.26 in X.org

### ISSUE THREAD

**Issue by webmastak** [hslbck/gnome-shell-extension-radio#78]
Manjaro 17.0.6 Gellivara, X.org, multimedia keys not work in Gnome 3.26. after update from Gnome 3.24.
With Gnome 3.24 worked well. 

How to solve a problem?

**Comment by stmc** [comment]
archlinux, also not work in 3.26

**Comment by hslbck** [comment]
Multimedia keys aren't working for me either on X. I have to check if there has been some API changes

**Comment by hslbck** [comment]
Media keys should work again on X.org with latest commit. On Wayland media keys only work after extension reload

**Comment by stmc** [comment]
works well, thanks

**Comment by webmastak** [comment]
works well, thanks!
