### ISSUE TITLE
`Add` displayed instead of `Save`

### ISSUE THREAD

**Issue by zapashcanon** [hslbck/gnome-shell-extension-radio#82]
Hi,

When editing a channel, `Add` is displayed when it should be `Save`.

From [this line](https://github.com/hslbck/gnome-shell-extension-radio/blob/master/radio%40hslbck.gmail.com/addChannelDialog.js#L111), I think that `oldChannel` is not updated properly and is always set to `NULL`.

**Comment by hslbck** [comment]
Ok it works for me. How did you reinstall the extension? Did you use Wayland when updating to the latest commit?

**Comment by zapashcanon** [comment]
Seems to work now (I didn't tried with master but with #83 and #86) so, I think I did something wrong when installing. I may had the extension installed two times (globally and for my user only). I'm not sure...

But, it works, so, closing. :)
