### ISSUE TITLE
Feature Request: Don't close dialog when searching then adding

### ISSUE THREAD

**Issue by thejacer87** [hslbck/gnome-shell-extension-radio#91]
When searching for streams, i found it annoying that the dialog closed every time i added a station.

Maybe just an annoyance for the first time installed. As it won't happen too much going forward.

**Comment by hslbck** [comment]
Thanks for your feedback. It probably makes sense to change the workflow here. When I've some spare time I'll change it.

**Comment by thejacer87** [comment]
just made the [PR](https://github.com/hslbck/gnome-shell-extension-radio/pull/93)

**Comment by hslbck** [comment]
merged PR and added a info message about the added station
