### ISSUE TITLE
gnome-shell freezes on ubuntu 17.10

### ISSUE THREAD

**Issue by thejacer87** [hslbck/gnome-shell-extension-radio#95]
just upgraded to ubuntu 17.10 and was able to add a station and turn it on, i could listen for a few minutes. then gnome froze. restarted the computer, and now gnome freezes immediately when starting a stream

turned off all extensions and still no luck. not sure how to get good/accurate logs

```
gnome-shell --version
GNOME Shell 3.26.2
```

**Comment by hslbck** [comment]
please check if this is the same issue as #75 Crash on Ubuntu 17.10 (Wayland)

**Comment by thejacer87** [comment]
ya sorry, im a dunce and clearly didn't look at the open issues. confirmed working on xorg, crash on wayland

closing the issue
